FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_AO/Cmd/Init/Init_S/FH_AO_Init_S.h File Reference
FH_AO_Init_S.h File Reference
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output), Cmd (Command), Init, Init_S (Init Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_Init_AO01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_AO/FH_AO_Configs/FH_AO_Configs.h"
Functions
void FH_AO_Init_S (FH_AO_Init_FuncPtrModel *FH_AO_Init_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_Init_AO01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output), Cmd (Command), Init, Init_S (Init Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_Init_AO01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AO_Init_S.h.
Function Documentation
FH_AO_Init_S()
void FH_AO_Init_S (FH_AO_Init_FuncPtrModel * FH_AO_Init_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_Init_AO01-... to an array of function pointers.
Parameters
FH_AO_Init_FuncPtr An array of function pointers with FH_AO_Init_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_AO_Init_S.c.
References FH_AO_Init_AO01(), FH_AO_Init_AO02(), FH_AO_Init_AO03(), FH_AO_Init_AO04(), FH_AO_Init_AO05(), FH_AO_Init_AO06(), FH_AO_Init_AO07(), FH_AO_Init_AO08(), FH_AO_Init_AO09(), FH_AO_Init_AO10(), FH_AO_Init_AO11(), FH_AO_Init_AO12(), FH_AO_Init_AO13(), FH_AO_Init_AO14(), FH_AO_Init_AO15(), FH_AO_Init_AO16(), FH_AO_Init_AO17(), FH_AO_Init_AO18(), FH_AO_Init_AO19(), FH_AO_Init_AO20(), FH_AO_Init_AO21(), FH_AO_Init_AO22(), FH_AO_Init_AO23(), FH_AO_Init_AO24(), FH_AO_Init_AO25(), FH_AO_Init_AO26(), FH_AO_Init_AO27(), FH_AO_Init_AO28(), FH_AO_Init_AO29(), FH_AO_Init_AO30(), FH_AO_Init_AO31(), FH_AO_Init_AO32(), FH_AO_MaxPeripheralNumber, and NULL_PTR.
Referenced by FH_AO_ProcessCommand_Init().