FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_DO/FH_DO55/FH_DO55.c File Reference
FH_DO55.c File Reference
File Map:
FH_Functions, Section FH_DO (Digital Output), Peripheral FH_DO55 (Digital Output 55)
(The DO55 (Digital Output 55) could be any interested digital output of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO55/FH_DO55.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_DO/FH_DO.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GlobalTimerCount/FH_GlobalTimerCount.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
Functions
FH_ErrorInfo FH_DO_Init_DO55 ()
This function initializes the Digital Output 55
The Digital Output 55 could be any interested digital output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested digital output here.
FH_ErrorInfo FH_DO_SetStatus_DO55 (uint8_t Status)
This function sets or resets the Digital Output 55
The Digital Output 55 could be any interested digital output of the micro-controller on which FH source code is ported
FH user should call the set and reset functions of the interested digital output here.
Detailed Description
File Map:
FH_Functions, Section FH_DO (Digital Output), Peripheral FH_DO55 (Digital Output 55)
(The DO55 (Digital Output 55) could be any interested digital output of the micro-controller on which FH source code is ported)
Note
To have a clean code, FH user should have the implementation of the initialization, set and reset functions of of the Digital Output 55 in a separate c file
Then FH user should include the header file (.h) of the related source file (.c) here
This header file shall include the following items:
The declaration of the initialization function of the Digital Output 55
The declaration of the set and reset functions of the Digital Output 55
Attention
There are a total number of 4 attentions (FH user defined code) in this file where FH user shall insert some code
Other parts could be left intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DO55.c.
Function Documentation
FH_DO_Init_DO55()
FH_ErrorInfo FH_DO_Init_DO55 ()
This function initializes the Digital Output 55
The Digital Output 55 could be any interested digital output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested digital output here.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DO55}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO55 => It indicates the Digital Output 55
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_Init => It is the command of the function in the message frame
Warning
To be able to set or reset the Digital Output 55 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_DO_SetStatus_DO55 function from RobotFramework, this function shall be invoked in order to initialize the digital output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 78 of file FH_DO55.c.
References FH_ResetErrorInfo().
Referenced by FH_DO_Init_S().
FH_DO_SetStatus_DO55()
FH_ErrorInfo FH_DO_SetStatus_DO55 (uint8_t Status)
This function sets or resets the Digital Output 55
The Digital Output 55 could be any interested digital output of the micro-controller on which FH source code is ported
FH user should call the set and reset functions of the interested digital output here.
Parameters
Status If Status is 1, the set function of the Digital Output 55 shall be called
If Status is 0, the reset function of the Digital Output 55 shall be called
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DO55}    ${DO_Set}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO55 => It indicates the Digital Output 55
  DO_Set => It indicates the Digital Output 55 shall be Set (DO_Reset indicates the Digital Output 55 shall be Reset)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatus => It is the command of the function in the message frame
Warning
To be able to set or reset the Digital Output 55 of the micro-controller on which FH source code is ported, the FH_DO_Init_DO55 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_DO_SetStatus_DO55 function from RobotFramework, FH_DO_Init_DO55 function shall be invoked in order to initialize the digital output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 130 of file FH_DO55.c.
References FH_ErrorInfo::error_code, FH_ERROR_MessageFrame, and FH_ResetErrorInfo().
Referenced by FH_DO_SetStatus_S().