FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_UART/FH_UART04/FH_UART04.h File Reference
FH_UART04.h File Reference
File Map:
FH_Functions, Section FH_UART, Peripheral FH_UART04 (UART 04)
(The UART04 (UART 04) could be any interested UART of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_UART/FH_UART_Configs/FH_UART_Configs.h"
#include "../../../../FH_Embedded/FH_Setup/FH_RFCommunication/FH_RFCommunication_GlobalVariables.h"
Functions
FH_ErrorInfo FH_UART_Init_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function initializes the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
FH_ErrorInfo FH_UART_Send_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sends data through the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
FH_ErrorInfo FH_UART_Receive_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *FH_DataSize, uint8_t *FH_Data)
This function retrieves the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_ReceiveW_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *FH_DataSize, uint8_t *FH_Data)
This function waits to receive the specified number of bytes of data through the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
A maximum timeout is specified too
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_ResetRB_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function resets the ISR (Interrupt Service Routine) receive buffer index (FH_UART04_ReceiveBufIndex) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_SSD8_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_8Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH_ErrorInfo FH_UART_SSD16_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_16Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_16Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH_ErrorInfo FH_UART_SSD32_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_32Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_32Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH_ErrorInfo FH_UART_GSD8_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_8Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH_ErrorInfo FH_UART_GSD16_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_16Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_16Bits is a shared global 16 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH_ErrorInfo FH_UART_GSD32_UART04 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_32Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_32Bits is a shared global 32 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
Detailed Description
File Map:
FH_Functions, Section FH_UART, Peripheral FH_UART04 (UART 04)
(The UART04 (UART 04) could be any interested UART of the micro-controller on which FH source code is ported)
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_UART04.h.
Function Documentation
FH_UART_GSD16_UART04()
FH_ErrorInfo FH_UART_GSD16_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_16Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_16Bits is a shared global 16 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART04_SharedDataBufLength_16Bits
SharedData *SharedData will be set to FH_UART04_SharedDataBuf_16Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_16Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD16}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD16 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 682 of file FH_UART04.c.
References FH_Uint8Uint16::bytes, FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART04_SharedDataBuf_16Bits, FH_UART04_SharedDataBufLength_16Bits, and FH_Uint8Uint16::value.
Referenced by FH_UART_GSD16_S().
FH_UART_GSD32_UART04()
FH_ErrorInfo FH_UART_GSD32_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_32Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_32Bits is a shared global 32 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART04_SharedDataBufLength_32Bits
SharedData *SharedData will be set to FH_UART04_SharedDataBuf_32Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_32Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD32}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD32 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 741 of file FH_UART04.c.
References FH_Uint8Uint32::bytes, FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART04_SharedDataBuf_32Bits, FH_UART04_SharedDataBufLength_32Bits, and FH_Uint8Uint32::value.
Referenced by FH_UART_GSD32_S().
FH_UART_GSD8_UART04()
FH_ErrorInfo FH_UART_GSD8_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART04_SharedDataBuf_8Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART04_SharedDataBufLength_8Bits
SharedData *SharedData will be set to FH_UART04_SharedDataBuf_8Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_8Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD8}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD8 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 627 of file FH_UART04.c.
References FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART04_SharedDataBuf_8Bits, and FH_UART04_SharedDataBufLength_8Bits.
Referenced by FH_UART_GSD8_S().
FH_UART_Init_UART04()
FH_ErrorInfo FH_UART_Init_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function initializes the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Init => It is the command of the function in the message frame
Warning
To be able to send or receive data through the UART 04 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking for example FH_UART_Send_UART04 or FH_UART_Receive_UART04 functions or ... from RobotFramework, this function shall be invoked in order to initialize the UART
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 126 of file FH_UART04.c.
References FH_ResetErrorInfo().
Referenced by FH_UART_Init_S().
FH_UART_Receive_UART04()
FH_ErrorInfo FH_UART_Receive_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * DataSize, uint8_t * Data)
This function retrieves the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
DataSize *DataSize will be set to the ISR (Interrupt Service Routine) receive buffer index (FH_UART04_ReceiveBufIndex) of the UART 04
Data *Data will be set to the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART04_ReceiveBuf and FH_UART04_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
In other word, FH_UART04_ReceiveBuf array shall receive every byte of the received data there with FH_UART04_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Receive}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Receive => It is the command of the function in the message frame
Warning
To be able to receive data through the UART 04 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART04 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_Receive_UART04 function from RobotFramework, FH_UART_Init_UART04 function shall be invoked in order to initialize the UART
Note
The only solution for resetting the receive buffer index (FH_UART04_ReceiveBufIndex) is using FH_UART_ResetRB_UART04 function
In other words, FH_UART04_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART04 through RobotFramework to reset the receive buffer index (FH_UART04_ReceiveBufIndex) before invoking FH_UART_Receive_UART04
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 256 of file FH_UART04.c.
References FH_ResetErrorInfo(), FH_UART04_ReceiveBuf, and FH_UART04_ReceiveBufIndex.
Referenced by FH_UART_Receive_S().
FH_UART_ReceiveW_UART04()
FH_ErrorInfo FH_UART_ReceiveW_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * DataSize, uint8_t * Data)
This function waits to receive the specified number of bytes of data through the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
A maximum timeout is specified too
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
DataSize *DataSize will be set to the ISR (Interrupt Service Routine) receive buffer index (FH_UART04_ReceiveBufIndex) of the UART 04
Data *Data will be set to the ISR (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the UART 04
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART04_ReceiveBuf and FH_UART04_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
In other word, FH_UART04_ReceiveBuf array shall receive every byte of the received data there with FH_UART04_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}    05    00    00    0B    B8
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_ReceiveW}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  05 => The expected number of bytes of data to be received through the <b>ISR</b> (Interrupt Service Routine) receive buffer (FH_UART04_ReceiveBuf) of the <b>UART 04</b>
  00    00    0B    B8 => Example data (0x00000BB8 mili-seconds) as timeout of receiving the expected number of bytes
                          FH_GlobalTimeCounter which is a global variable is utilized to calculate the timeout
                          FH_GlobalTimeCounter shall be incremented every <b>1 mili-second</b> in an interested timer <b>ISR</b> (Interrupt Service Routine) by <b>FH</b> user
                          For this to happen, <b>FH_GlobalTimerCount.h</b> shall be included in the interested timer <b>ISR</b> (Interrupt Service Routine) file
                          If the expected number of bytes are received, the function does not wait anymore for the remaining time of the timeout
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_ReceiveW => It is the command of the function in the message frame
Warning
To be able to receive data through the UART 04 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART04 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_ReceiveW_UART04 function from RobotFramework, FH_UART_Init_UART04 function shall be invoked in order to initialize the UART
Note
The only solution for resetting the receive buffer index (FH_UART04_ReceiveBufIndex) is using FH_UART_ResetRB_UART04 function
In other words, FH_UART04_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART04 through RobotFramework to reset the receive buffer index (FH_UART04_ReceiveBufIndex) before invoking FH_UART_ReceiveW_UART04
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 327 of file FH_UART04.c.
References FH_ConvertUint8ToUint32(), FH_GlobalTimeCounter, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART04_ReceiveBuf, FH_UART04_ReceiveBufIndex, UART_ReceiveW_ExpectedDataLength, and UART_ReceiveW_MaxTimerCount.
Referenced by FH_UART_ReceiveW_S().
FH_UART_ResetRB_UART04()
FH_ErrorInfo FH_UART_ResetRB_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function resets the ISR (Interrupt Service Routine) receive buffer index (FH_UART04_ReceiveBufIndex) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART04_ReceiveBuf and FH_UART04_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
In other word, FH_UART04_ReceiveBuf array shall receive every byte of the received data there with FH_UART04_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_ResetRB}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_ResetRB => It is the command of the function in the message frame
Warning
The only solution for resetting the receive buffer index (FH_UART04_ReceiveBufIndex) is using FH_UART_ResetRB_UART04 function
In other words, FH_UART04_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART04 through RobotFramework to reset the receive buffer index (FH_UART04_ReceiveBufIndex) before invoking FH_UART_Receive_UART04 or FH_UART_ReceiveW_UART04 or ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 394 of file FH_UART04.c.
References FH_ResetErrorInfo(), and FH_UART04_ReceiveBufIndex.
Referenced by FH_UART_ResetRB_S().
FH_UART_Send_UART04()
FH_ErrorInfo FH_UART_Send_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sends data through the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}    02    B1     FF
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Send}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  02 => Example length of the data to be sent
  B1     FF => Example data (0xB1, 0xFF) to be sent (or apart from the data to be sent, it may include some other data like ID, Filter, ... to be processed too, if need be) through the <b>UART 04</b>\n
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Send => It is the command of the function in the message frame
Warning
To be able to send data through the UART 04 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART04 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_Send_UART04 function from RobotFramework, FH_UART_Init_UART04 function shall be invoked in order to initialize the UART
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 179 of file FH_UART04.c.
References FH_ResetErrorInfo(), fh_RFCommunication_Message, UART_Send_Data, and UART_Send_DataLength.
Referenced by FH_UART_Send_S().
FH_UART_SSD16_UART04()
FH_ErrorInfo FH_UART_SSD16_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_16Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_16Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_16Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}    02    AA    BB    CC    DD
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD16}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  02 => Example interested length of the 16 bit data to be set
  AA    BB    CC    DD => Example data (0xAABB and 0xCCDD) to be set in <b>FH_UART04_SharedDataBuf_16Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD16 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 500 of file FH_UART04.c.
References FH_ErrorInfo::error_code, FH_ConvertUint8ToUint16(), FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART04_SharedDataBuf_16Bits, FH_UART04_SharedDataBufLength_16Bits, UART_SSD16_SharedData, and UART_SSD16_SharedDataLength.
Referenced by FH_UART_SSD16_S().
FH_UART_SSD32_UART04()
FH_ErrorInfo FH_UART_SSD32_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_32Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_32Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_32Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}    02    AA    BB    CC    DD    01    02    03    04
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD32}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  02 => Example interested length of the 32 bit data to be set
  AA    BB    CC    DD    01    02    03    04 => Example data (0xAABBCCDD and 0x01020304) to be set in <b>FH_UART04_SharedDataBuf_32Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD32 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 562 of file FH_UART04.c.
References FH_ErrorInfo::error_code, FH_ConvertUint8ToUint32(), FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART04_SharedDataBuf_32Bits, FH_UART04_SharedDataBufLength_32Bits, UART_SSD32_SharedData, and UART_SSD32_SharedDataLength.
Referenced by FH_UART_SSD32_S().
FH_UART_SSD8_UART04()
FH_ErrorInfo FH_UART_SSD8_UART04 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART04_SharedDataBuf_8Bits) of the UART 04
The UART 04 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART04_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART04_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 04 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART04_SharedDataBuf_8Bits in the receive ISR (Interrupt Service Routine) of the UART 04 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART04_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART04}    04    AA    BB    CC    DD
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD8}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART04 => It indicates the UART 04
  04 => Example interested length of the 8 bit data to be set
  AA    BB    CC    DD => Example data (0xAA, 0xBB, 0xCC, 0xDD) to be set in <b>FH_UART04_SharedDataBuf_8Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD8 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 442 of file FH_UART04.c.
References FH_ErrorInfo::error_code, FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART04_SharedDataBuf_8Bits, FH_UART04_SharedDataBufLength_8Bits, UART_SSD8_SharedData, and UART_SSD8_SharedDataLength.
Referenced by FH_UART_SSD8_S().