FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH/FH_Root/FH_Perif/FH_DI/Cmd/GetStatus/GetStatus_R/FH_DI_GetStatus_R.h File Reference
FH_DI_GetStatus_R.h File Reference
#include "../../../../../../FH_Root/FH_Perif/FH_DI/FH_DI_Configs/FH_DI_Configs.h"
Functions
FH_ErrorInfo FH_DI_GetStatus_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *FH_DI_Data, FH_DI_GetStatus_FuncPtrModel *FH_DI_GetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
FH_ErrorInfo FH_DI_GetStatusMULTI_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *FH_DI_MULTIData, FH_DI_GetStatus_FuncPtrModel *FH_DI_GetStatus_FuncPtr)
This function Calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the 8 first parameters of the Data in the message frame
(The first 8 parameters as mask resemble 64 bits and each bit resembles 1 DI (Digital Input) and if the bit is 1, the related DI (Digital Input) function will be called)
Function Documentation
FH_DI_GetStatus_R_Start()
FH_ErrorInfo FH_DI_GetStatus_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * FH_DI_Data, FH_DI_GetStatus_FuncPtrModel * FH_DI_GetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DI_GetStatus_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    DI01
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_GetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DI01 => It indicates the Digital Input 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_GetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 57 of file FH_DI_GetStatus_R.c.
References FH_ErrorInfo::error_code, FH_DI_MaxPeripheralNumber, FH_ERROR_CommandData, FH_ERROR_Functions, FH_ERROR_NoInfo, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DI_ProcessCommand_GetStatus().
FH_DI_GetStatusMULTI_R_Start()
FH_ErrorInfo FH_DI_GetStatusMULTI_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * FH_DI_MULTIData, FH_DI_GetStatus_FuncPtrModel * FH_DI_GetStatus_FuncPtr)
This function Calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the 8 first parameters of the Data in the message frame
(The first 8 parameters as mask resemble 64 bits and each bit resembles 1 DI (Digital Input) and if the bit is 1, the related DI (Digital Input) function will be called)
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DI_GetStatus_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    FF    FF    FF    FF    FF    FF    FF    FF
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_GetStatusMULTI}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  FF    FF    FF    FF    FF    FF    FF    FF => Example data as the first 8 parameters
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_GetStatusMULTI => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 114 of file FH_DI_GetStatus_R.c.
References FH_DI_MaxPeripheralNumber, FH_DI_MULTI_MaxPeripheralNumberLimit, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DI_ProcessCommand_GetStatusMULTI().