FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_UART/FH_UART01/FH_UART01.c File Reference
FH_UART01.c File Reference
File Map:
FH_Functions, Section FH_UART, Peripheral FH_UART01 (UART 01)
(The UART01 (UART 01) could be any interested UART of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART01/FH_UART01.h"
#include "usart.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_UART/FH_UART.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GlobalTimerCount/FH_GlobalTimerCount.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART01/FH_UART01_Configs.h"
#include "../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART01/FH_UART01_GlobalVariables.h"
Functions
FH_ErrorInfo FH_UART_Init_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function initializes the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
FH_ErrorInfo FH_UART_Send_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sends data through the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
FH_ErrorInfo FH_UART_Receive_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *DataSize, uint8_t *Data)
This function retrieves the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_ReceiveW_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *DataSize, uint8_t *Data)
This function waits to receive the specified number of bytes of data through the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
A maximum timeout is specified too
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_ResetRB_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function resets the ISR (Interrupt Service Routine) receive buffer index (FH_UART01_ReceiveBufIndex) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
FH_ErrorInfo FH_UART_SSD8_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_8Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH_ErrorInfo FH_UART_SSD16_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_16Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_16Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH_ErrorInfo FH_UART_SSD32_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_32Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_32Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH_ErrorInfo FH_UART_GSD8_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_8Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH_ErrorInfo FH_UART_GSD16_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_16Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_16Bits is a shared global 16 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH_ErrorInfo FH_UART_GSD32_UART01 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint8_t *SharedDataLength, uint8_t *SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_32Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_32Bits is a shared global 32 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
Variables
volatile uint8_t FH_UART01_ReceiveBuf [FH_UART01_ReceiveBufLength]
volatile uint16_t FH_UART01_ReceiveBufIndex = 0
volatile uint8_t FH_UART01_SharedDataBuf_8Bits [FH_UART01_SharedDataBufLength_8Bits]
volatile uint16_t FH_UART01_SharedDataBuf_16Bits [FH_UART01_SharedDataBufLength_16Bits]
volatile uint32_t FH_UART01_SharedDataBuf_32Bits [FH_UART01_SharedDataBufLength_32Bits]
Detailed Description
File Map:
FH_Functions, Section FH_UART, Peripheral FH_UART01 (UART 01)
(The UART01 (UART 01) could be any interested UART of the micro-controller on which FH source code is ported)
Note
To have a clean code, FH user should have the implementation of the initialization and send functions of the UART 01 in a separate c file
Then FH user should include the header file (.h) of the related source file (.c) here
This header file shall include the following items:
The declaration of the initialization function of the UART 01
The declaration of the send function of the UART 01
FH user shall use FH_UART01_ReceiveBuf and FH_UART01_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there In other word, FH_UART01_ReceiveBuf array shall receive every byte of the received data there with FH_UART01_ReceiveBufIndex as index of the array
FH_UART01_SharedDataBuf_8Bits, FH_UART01_SharedDataBuf_16Bits and FH_UART01_SharedDataBuf_32Bits are optional and could be left intact
They could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 , ...
They are controllable with some commands (described in this file) through RobotFramework
Attention
There are a total number of 3 attentions (FH user defined code) in this file where FH user shall insert some code
Other parts could be left intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_UART01.c.
Function Documentation
FH_UART_GSD16_UART01()
FH_ErrorInfo FH_UART_GSD16_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_16Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_16Bits is a shared global 16 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART01_SharedDataBufLength_16Bits
SharedData *SharedData will be set to FH_UART01_SharedDataBuf_16Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_16Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD16}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD16 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 681 of file FH_UART01.c.
References FH_Uint8Uint16::bytes, FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART01_SharedDataBuf_16Bits, FH_UART01_SharedDataBufLength_16Bits, and FH_Uint8Uint16::value.
Referenced by FH_UART_GSD16_S().
FH_UART_GSD32_UART01()
FH_ErrorInfo FH_UART_GSD32_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_32Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_32Bits is a shared global 32 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART01_SharedDataBufLength_32Bits
SharedData *SharedData will be set to FH_UART01_SharedDataBuf_32Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_32Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD32}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD32 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 740 of file FH_UART01.c.
References FH_Uint8Uint32::bytes, FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART01_SharedDataBuf_32Bits, FH_UART01_SharedDataBufLength_32Bits, and FH_Uint8Uint32::value.
Referenced by FH_UART_GSD32_S().
FH_UART_GSD8_UART01()
FH_ErrorInfo FH_UART_GSD8_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * SharedDataLength, uint8_t * SharedData)
This function gets the shared data buffer (FH_UART01_SharedDataBuf_8Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
SharedDataLength *SharedDataLength will be set to FH_UART01_SharedDataBufLength_8Bits
SharedData *SharedData will be set to FH_UART01_SharedDataBuf_8Bits
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_8Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_GSD8}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_GSD8 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 626 of file FH_UART01.c.
References FH_ErrorInfo::error_code, FH_ERROR_OK, FH_ResetErrorInfo(), FH_UART01_SharedDataBuf_8Bits, and FH_UART01_SharedDataBufLength_8Bits.
Referenced by FH_UART_GSD8_S().
FH_UART_Init_UART01()
FH_ErrorInfo FH_UART_Init_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function initializes the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Init => It is the command of the function in the message frame
Warning
To be able to send or receive data through the UART 01 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking for example FH_UART_Send_UART01 or FH_UART_Receive_UART01 functions or ... from RobotFramework, this function shall be invoked in order to initialize the UART
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 127 of file FH_UART01.c.
References FH_ResetErrorInfo().
Referenced by FH_UART_Init_S().
FH_UART_Receive_UART01()
FH_ErrorInfo FH_UART_Receive_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * DataSize, uint8_t * Data)
This function retrieves the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
DataSize *DataSize will be set to the ISR (Interrupt Service Routine) receive buffer index (FH_UART01_ReceiveBufIndex) of the UART 01
Data *Data will be set to the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART01_ReceiveBuf and FH_UART01_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
In other word, FH_UART01_ReceiveBuf array shall receive every byte of the received data there with FH_UART01_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Receive}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Receive => It is the command of the function in the message frame
Warning
To be able to receive data through the UART 01 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART01 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_Receive_UART01 function from RobotFramework, FH_UART_Init_UART01 function shall be invoked in order to initialize the UART
Note
The only solution for resetting the receive buffer index (FH_UART01_ReceiveBufIndex) is using FH_UART_ResetRB_UART01 function
In other words, FH_UART01_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART01 through RobotFramework to reset the receive buffer index (FH_UART01_ReceiveBufIndex) before invoking FH_UART_Receive_UART01
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 255 of file FH_UART01.c.
References FH_ResetErrorInfo(), FH_UART01_ReceiveBuf, and FH_UART01_ReceiveBufIndex.
Referenced by FH_UART_Receive_S().
FH_UART_ReceiveW_UART01()
FH_ErrorInfo FH_UART_ReceiveW_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint8_t * DataSize, uint8_t * Data)
This function waits to receive the specified number of bytes of data through the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
A maximum timeout is specified too
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
DataSize *DataSize will be set to the ISR (Interrupt Service Routine) receive buffer index (FH_UART01_ReceiveBufIndex) of the UART 01
Data *Data will be set to the ISR (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the UART 01
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART01_ReceiveBuf and FH_UART01_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
In other word, FH_UART01_ReceiveBuf array shall receive every byte of the received data there with FH_UART01_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}    05    00    00    0B    B8
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_ReceiveW}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  05 => The expected number of bytes of data to be received through the <b>ISR</b> (Interrupt Service Routine) receive buffer (FH_UART01_ReceiveBuf) of the <b>UART 01</b>
  00    00    0B    B8 => Example data (0x00000BB8 mili-seconds) as timeout of receiving the expected number of bytes
                          FH_GlobalTimeCounter which is a global variable is utilized to calculate the timeout
                          FH_GlobalTimeCounter shall be incremented every <b>1 mili-second</b> in an interested timer <b>ISR</b> (Interrupt Service Routine) by <b>FH</b> user
                          For this to happen, <b>FH_GlobalTimerCount.h</b> shall be included in the interested timer <b>ISR</b> (Interrupt Service Routine) file
                          If the expected number of bytes are received, the function does not wait anymore for the remaining time of the timeout
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_ReceiveW => It is the command of the function in the message frame
Warning
To be able to receive data through the UART 01 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART01 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_ReceiveW_UART01 function from RobotFramework, FH_UART_Init_UART01 function shall be invoked in order to initialize the UART
Note
The only solution for resetting the receive buffer index (FH_UART01_ReceiveBufIndex) is using FH_UART_ResetRB_UART01 function
In other words, FH_UART01_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART01 through RobotFramework to reset the receive buffer index (FH_UART01_ReceiveBufIndex) before invoking FH_UART_ReceiveW_UART01
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 326 of file FH_UART01.c.
References FH_ConvertUint8ToUint32(), FH_GlobalTimeCounter, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART01_ReceiveBuf, FH_UART01_ReceiveBufIndex, UART_ReceiveW_ExpectedDataLength, and UART_ReceiveW_MaxTimerCount.
Referenced by FH_UART_ReceiveW_S().
FH_UART_ResetRB_UART01()
FH_ErrorInfo FH_UART_ResetRB_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function resets the ISR (Interrupt Service Routine) receive buffer index (FH_UART01_ReceiveBufIndex) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user could left the present source code here intact.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_UART01_ReceiveBuf and FH_UART01_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
In other word, FH_UART01_ReceiveBuf array shall receive every byte of the received data there with FH_UART01_ReceiveBufIndex as index of the array
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_ResetRB}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_ResetRB => It is the command of the function in the message frame
Warning
The only solution for resetting the receive buffer index (FH_UART01_ReceiveBufIndex) is using FH_UART_ResetRB_UART01 function
In other words, FH_UART01_ReceiveBufIndex may have been already increased if any data has been already received
So it is normally required to invoke FH_UART_ResetRB_UART01 through RobotFramework to reset the receive buffer index (FH_UART01_ReceiveBufIndex) before invoking FH_UART_Receive_UART01 or FH_UART_ReceiveW_UART01 or ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 393 of file FH_UART01.c.
References FH_ResetErrorInfo(), and FH_UART01_ReceiveBufIndex.
Referenced by FH_UART_ResetRB_S().
FH_UART_Send_UART01()
FH_ErrorInfo FH_UART_Send_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sends data through the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}    02    B1     FF
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_Send}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  02 => Example length of the data to be sent
  B1     FF => Example data (0xB1, 0xFF) to be sent (or apart from the data to be sent, it may include some other data like ID, Filter, ... to be processed too, if need be) through the <b>UART 01</b>\n
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_Send => It is the command of the function in the message frame
Warning
To be able to send data through the UART 01 of the micro-controller on which FH source code is ported, the FH_UART_Init_UART01 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_UART_Send_UART01 function from RobotFramework, FH_UART_Init_UART01 function shall be invoked in order to initialize the UART
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 178 of file FH_UART01.c.
References FH_ResetErrorInfo(), fh_RFCommunication_Message, UART_Send_Data, and UART_Send_DataLength.
Referenced by FH_UART_Send_S().
FH_UART_SSD16_UART01()
FH_ErrorInfo FH_UART_SSD16_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_16Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_16Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_16Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_16Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}    02    AA    BB    CC    DD
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD16}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  02 => Example interested length of the 16 bit data to be set
  AA    BB    CC    DD => Example data (0xAABB and 0xCCDD) to be set in <b>FH_UART01_SharedDataBuf_16Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD16 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 499 of file FH_UART01.c.
References FH_ErrorInfo::error_code, FH_ConvertUint8ToUint16(), FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART01_SharedDataBuf_16Bits, FH_UART01_SharedDataBufLength_16Bits, UART_SSD16_SharedData, and UART_SSD16_SharedDataLength.
Referenced by FH_UART_SSD16_S().
FH_UART_SSD32_UART01()
FH_ErrorInfo FH_UART_SSD32_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_32Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_32Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_32Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_32Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}    02    AA    BB    CC    DD    01    02    03    04
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD32}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  02 => Example interested length of the 32 bit data to be set
  AA    BB    CC    DD    01    02    03    04 => Example data (0xAABBCCDD and 0x01020304) to be set in <b>FH_UART01_SharedDataBuf_32Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD32 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 561 of file FH_UART01.c.
References FH_ErrorInfo::error_code, FH_ConvertUint8ToUint32(), FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART01_SharedDataBuf_32Bits, FH_UART01_SharedDataBufLength_32Bits, UART_SSD32_SharedData, and UART_SSD32_SharedDataLength.
Referenced by FH_UART_SSD32_S().
FH_UART_SSD8_UART01()
FH_ErrorInfo FH_UART_SSD8_UART01 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the shared data buffer (FH_UART01_SharedDataBuf_8Bits) of the UART 01
The UART 01 could be any interested UART of the micro-controller on which FH source code is ported
FH_UART01_SharedDataBuf_8Bits is a shared global 8 bit array which is a data bridge between RobotFramework and FH user code
FH_UART01_SharedDataBuf_8Bits is optional
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 or ...
FH user could left the present source code here intact
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
FH user could use FH_UART01_SharedDataBuf_8Bits in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file or anywhere else interested
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${UART01}    04    AA    BB    CC    DD
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_UART}    Command=${UART_Commands_SSD8}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  UART01 => It indicates the UART 01
  04 => Example interested length of the 8 bit data to be set
  AA    BB    CC    DD => Example data (0xAA, 0xBB, 0xCC, 0xDD) to be set in <b>FH_UART01_SharedDataBuf_8Bits</b>
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_UART => It is the function in the message frame
  UART_Commands_SSD8 => It is the command of the function in the message frame
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 441 of file FH_UART01.c.
References FH_ErrorInfo::error_code, FH_ERROR_Functions, FH_ERROR_OK, FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_UART01_SharedDataBuf_8Bits, FH_UART01_SharedDataBufLength_8Bits, UART_SSD8_SharedData, and UART_SSD8_SharedDataLength.
Referenced by FH_UART_SSD8_S().
Variable Documentation
FH_UART01_ReceiveBuf
volatile uint8_t FH_UART01_ReceiveBuf[FH_UART01_ReceiveBufLength]
FH user shall use FH_UART01_ReceiveBuf in the receive ISR (Interrupt Service Routine) of the UART 01 in a separate c file
For this to happen, FH user shall just include FH_UART01_GlobalVariables.h there
In other word, FH_UART01_ReceiveBuf array shall receive every byte of the received data there
It is configurable in FH_UART0_Configs.h
Definition at line 60 of file FH_UART01.c.
Referenced by FH_UART_Receive_UART01(), and FH_UART_ReceiveW_UART01().
FH_UART01_ReceiveBufIndex
volatile uint16_t FH_UART01_ReceiveBufIndex = 0
FH_UART01_ReceiveBufIndex is the index of FH_UART01_ReceiveBuf
Definition at line 65 of file FH_UART01.c.
Referenced by FH_UART_Receive_UART01(), FH_UART_ReceiveW_UART01(), and FH_UART_ResetRB_UART01().
FH_UART01_SharedDataBuf_16Bits
volatile uint16_t FH_UART01_SharedDataBuf_16Bits[FH_UART01_SharedDataBufLength_16Bits]
FH_UART01_SharedDataBuf_16Bits is optional and could be left intact
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 , ... It are controllable with some commands (described in this file) through RobotFramework
It is configurable in FH_UART0_Configs.h
Definition at line 81 of file FH_UART01.c.
Referenced by FH_UART_GSD16_UART01(), and FH_UART_SSD16_UART01().
FH_UART01_SharedDataBuf_32Bits
volatile uint32_t FH_UART01_SharedDataBuf_32Bits[FH_UART01_SharedDataBufLength_32Bits]
FH_UART01_SharedDataBuf_32Bits is optional and could be left intact
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 , ... It are controllable with some commands (described in this file) through RobotFramework
It is configurable in FH_UART0_Configs.h
Definition at line 88 of file FH_UART01.c.
Referenced by FH_UART_GSD32_UART01(), and FH_UART_SSD32_UART01().
FH_UART01_SharedDataBuf_8Bits
volatile uint8_t FH_UART01_SharedDataBuf_8Bits[FH_UART01_SharedDataBufLength_8Bits]
FH_UART01_SharedDataBuf_8Bits is optional and could be left intact
It could be used by FH user to set some special data like receive filters on ISR (Interrupt Service Routine) of the UART 01 , ... It are controllable with some commands (described in this file) through RobotFramework
It is configurable in FH_UART0_Configs.h
Definition at line 73 of file FH_UART01.c.
Referenced by FH_UART_GSD8_UART01(), and FH_UART_SSD8_UART01().