FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_AO/FH_AO15/FH_AO15.c File Reference
FH_AO15.c File Reference
File Map:
FH_Functions, Section FH_AO (Analog Output), Peripheral FH_AO15 (Analog Output 15)
(The AO15 (Analog Output 15) could be any interested Analog Output of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO15/FH_AO15.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AO/FH_AO.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GlobalTimerCount/FH_GlobalTimerCount.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
Functions
FH_ErrorInfo FH_AO_Init_AO15 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function initializes the Analog Output 15
The Analog Output 15 could be any interested Analog Output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested Analog Output here.
FH_ErrorInfo FH_AO_SetStatus_AO15 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the Analog Output 15
The Analog Output 15 could be any interested Analog Output of the micro-controller on which FH source code is ported
FH user should call the set function of the interested Analog Output here.
Detailed Description
File Map:
FH_Functions, Section FH_AO (Analog Output), Peripheral FH_AO15 (Analog Output 15)
(The AO15 (Analog Output 15) could be any interested Analog Output of the micro-controller on which FH source code is ported)
Note
To have a clean code, FH user should have the implementation of the initialization and set function of of the Analog Output 15 in a separate c file
Then FH user should include the header file (.h) of the related source file (.c) here
This header file shall include the following items:
The declaration of the initialization function of the Analog Output 15
The declaration of the set function of the Analog Output 15
Attention
There are a total number of 3 attentions (FH user defined code) in this file where FH user shall insert some code
Other parts could be left intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AO15.c.
Function Documentation
FH_AO_Init_AO15()
FH_ErrorInfo FH_AO_Init_AO15 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function initializes the Analog Output 15
The Analog Output 15 could be any interested Analog Output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested Analog Output here.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AO15}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AO}    Command=${AO_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AO15 => It indicates the Analog Output 15
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AO => It is the function in the message frame
  AO_Commands_Init => It is the command of the function in the message frame
Warning
To be able to set or reset the Analog Output 15 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_AO_SetStatus_AO15 function from RobotFramework, this function shall be invoked in order to initialize the Analog Output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 78 of file FH_AO15.c.
References FH_ResetErrorInfo().
Referenced by FH_AO_Init_S().
FH_AO_SetStatus_AO15()
FH_ErrorInfo FH_AO_SetStatus_AO15 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the Analog Output 15
The Analog Output 15 could be any interested Analog Output of the micro-controller on which FH source code is ported
FH user should call the set function of the interested Analog Output here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AO15}    F1    C2    01    08
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AO}    Command=${AO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AO15 => It indicates the Analog Output 15
  F1    C2    01    08 => Example data as analog value (0xF1C20108) to be set through the <b>Analog Output 15</b>\n
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AO => It is the function in the message frame
  AO_Commands_SetStatus => It is the command of the function in the message frame
Warning
To be able to set the Analog Output 15 of the micro-controller on which FH source code is ported, the FH_AO_Init_AO15 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_AO_SetStatus_AO15 function from RobotFramework, FH_AO_Init_AO15 function shall be invoked in order to initialize the Analog Output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 130 of file FH_AO15.c.
References FH_ResetErrorInfo().
Referenced by FH_AO_SetStatus_S().