FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_PWMI/Cmd/GetStatus/GetStatus_S/FH_PWMI_GetStatus_S.c File Reference
FH_PWMI_GetStatus_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_PWMI (PWM Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMI (PWM Input), FH_PWMI_GetStatus_PWMI01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_PWMI/Cmd/GetStatus/GetStatus_S/FH_PWMI_GetStatus_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI01/FH_PWMI01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI02/FH_PWMI02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI03/FH_PWMI03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI04/FH_PWMI04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI05/FH_PWMI05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI06/FH_PWMI06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI07/FH_PWMI07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI08/FH_PWMI08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI09/FH_PWMI09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI10/FH_PWMI10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI11/FH_PWMI11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI12/FH_PWMI12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI13/FH_PWMI13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI14/FH_PWMI14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI15/FH_PWMI15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI16/FH_PWMI16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI17/FH_PWMI17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI18/FH_PWMI18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI19/FH_PWMI19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI20/FH_PWMI20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI21/FH_PWMI21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI22/FH_PWMI22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI23/FH_PWMI23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI24/FH_PWMI24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI25/FH_PWMI25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI26/FH_PWMI26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI27/FH_PWMI27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI28/FH_PWMI28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI29/FH_PWMI29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI30/FH_PWMI30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI31/FH_PWMI31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI32/FH_PWMI32.h"
Functions
void FH_PWMI_GetStatus_S (FH_PWMI_GetStatus_FuncPtrModel *FH_PWMI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMI (PWM Input), FH_PWMI_GetStatus_PWMI01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_PWMI (PWM Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMI (PWM Input), FH_PWMI_GetStatus_PWMI01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_PWMI_GetStatus_S.c.
Function Documentation
FH_PWMI_GetStatus_S()
void FH_PWMI_GetStatus_S (FH_PWMI_GetStatus_FuncPtrModel * FH_PWMI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMI (PWM Input), FH_PWMI_GetStatus_PWMI01-... to an array of function pointers.
Parameters
FH_PWMI_GetStatus_FuncPtr An array of function pointers with FH_PWMI_GetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_PWMI_GetStatus_S.c.
References FH_PWMI_GetStatus_PWMI01(), FH_PWMI_GetStatus_PWMI02(), FH_PWMI_GetStatus_PWMI03(), FH_PWMI_GetStatus_PWMI04(), FH_PWMI_GetStatus_PWMI05(), FH_PWMI_GetStatus_PWMI06(), FH_PWMI_GetStatus_PWMI07(), FH_PWMI_GetStatus_PWMI08(), FH_PWMI_GetStatus_PWMI09(), FH_PWMI_GetStatus_PWMI10(), FH_PWMI_GetStatus_PWMI11(), FH_PWMI_GetStatus_PWMI12(), FH_PWMI_GetStatus_PWMI13(), FH_PWMI_GetStatus_PWMI14(), FH_PWMI_GetStatus_PWMI15(), FH_PWMI_GetStatus_PWMI16(), FH_PWMI_GetStatus_PWMI17(), FH_PWMI_GetStatus_PWMI18(), FH_PWMI_GetStatus_PWMI19(), FH_PWMI_GetStatus_PWMI20(), FH_PWMI_GetStatus_PWMI21(), FH_PWMI_GetStatus_PWMI22(), FH_PWMI_GetStatus_PWMI23(), FH_PWMI_GetStatus_PWMI24(), FH_PWMI_GetStatus_PWMI25(), FH_PWMI_GetStatus_PWMI26(), FH_PWMI_GetStatus_PWMI27(), FH_PWMI_GetStatus_PWMI28(), FH_PWMI_GetStatus_PWMI29(), FH_PWMI_GetStatus_PWMI30(), FH_PWMI_GetStatus_PWMI31(), FH_PWMI_GetStatus_PWMI32(), FH_PWMI_MaxPeripheralNumber, and NULL_PTR.
Referenced by FH_PWMI_ProcessCommand_GetStatus().