FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_DI/Cmd/GetStatus/GetStatus_H/FH_DI_GetStatus_H.h File Reference
FH_DI_GetStatus_H.h File Reference
File Map:
FH_Root, Section FH_Perif, FH_DI (Digital Input), Cmd (Command), GetStatus, GetStatus_H (GetStatus Health)
Functions in this file, verify the health of the different message frames related to DI (Digital Input)
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_DI/FH_DI_Configs/FH_DI_Configs.h"
Functions
FH_ErrorInfo FH_DI_GetStatus_H (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function verifies the health of FH_DI_Commands_GetStatus command.
FH_ErrorInfo FH_DI_GetStatusMULTI_H (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function verifies the health of FH_DI_Commands_GetStatusMULTI command.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_DI (Digital Input), Cmd (Command), GetStatus, GetStatus_H (GetStatus Health)
Functions in this file, verify the health of the different message frames related to DI (Digital Input)
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DI_GetStatus_H.h.
Function Documentation
FH_DI_GetStatus_H()
FH_ErrorInfo FH_DI_GetStatus_H (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function verifies the health of FH_DI_Commands_GetStatus command.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DI01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_GetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DI01 => It indicates the Digital Input 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_GetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 56 of file FH_DI_GetStatus_H.c.
References FH_ErrorInfo::error_code, FH_DI_MaxPeripheralNumber, FH_DI_MinCommandSize_GetStatus, FH_ERROR_MessageFrame, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_DI_ProcessCommand_GetStatus().
FH_DI_GetStatusMULTI_H()
FH_ErrorInfo FH_DI_GetStatusMULTI_H (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function verifies the health of FH_DI_Commands_GetStatusMULTI command.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    FF    FF    FF    FF    FF    FF    FF    FF
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_GetStatusMULTI}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  FF    FF    FF    FF    FF    FF    FF    FF => Example data as the first 8 parameters
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_GetStatusMULTI => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 110 of file FH_DI_GetStatus_H.c.
References FH_ErrorInfo::error_code, FH_DI_MinCommandSize_GetStatusMULTI, FH_ERROR_MessageFrame, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_DI_ProcessCommand_GetStatusMULTI().