FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_CAN/Cmd/Send/Send_S/FH_CAN_Send_S.h File Reference
FH_CAN_Send_S.h File Reference
File Map:
FH_Root, Section FH_Perif, FH_CAN (Digital Output), Cmd (Command), Send, Send_S (Send Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_CAN (CAN), FH_CAN_Send_CAN01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_CAN/FH_CAN_Configs/FH_CAN_Configs.h"
Functions
void FH_CAN_Send_S (FH_CAN_Send_FuncPtrModel *FH_CAN_Send_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_CAN (CAN), FH_CAN_Send_CAN01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_CAN (Digital Output), Cmd (Command), Send, Send_S (Send Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_CAN (CAN), FH_CAN_Send_CAN01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_CAN_Send_S.h.
Function Documentation
FH_CAN_Send_S()
void FH_CAN_Send_S (FH_CAN_Send_FuncPtrModel * FH_CAN_Send_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_CAN (CAN), FH_CAN_Send_CAN01-... to an array of function pointers.
Parameters
FH_CAN_Send_FuncPtr An array of function pointers with FH_CAN_Send_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 64 of file FH_CAN_Send_S.c.
References FH_CAN_MaxPeripheralNumber, FH_CAN_Send_CAN01(), FH_CAN_Send_CAN02(), FH_CAN_Send_CAN03(), FH_CAN_Send_CAN04(), and NULL_PTR.
Referenced by FH_CAN_ProcessCommand_Send().