FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_PWMO/Cmd/SetStatus/SetStatus_S/FH_PWMO_SetStatus_S.h File Reference
FH_PWMO_SetStatus_S.h File Reference
File Map:
FH_Root, Section FH_Perif, FH_PWMO (PWM Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_SetStatus_PWMO01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_PWMO/FH_PWMO_Configs/FH_PWMO_Configs.h"
Functions
void FH_PWMO_SetStatus_S (FH_PWMO_SetStatus_FuncPtrModel *FH_PWMO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_SetStatus_PWMO01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_PWMO (PWM Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_SetStatus_PWMO01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_PWMO_SetStatus_S.h.
Function Documentation
FH_PWMO_SetStatus_S()
void FH_PWMO_SetStatus_S (FH_PWMO_SetStatus_FuncPtrModel * FH_PWMO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_SetStatus_PWMO01-... to an array of function pointers.
Parameters
FH_PWMO_SetStatus_FuncPtr An array of function pointers with FH_PWMO_SetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_PWMO_SetStatus_S.c.
References FH_PWMO_MaxPeripheralNumber, FH_PWMO_SetStatus_PWMO01(), FH_PWMO_SetStatus_PWMO02(), FH_PWMO_SetStatus_PWMO03(), FH_PWMO_SetStatus_PWMO04(), FH_PWMO_SetStatus_PWMO05(), FH_PWMO_SetStatus_PWMO06(), FH_PWMO_SetStatus_PWMO07(), FH_PWMO_SetStatus_PWMO08(), FH_PWMO_SetStatus_PWMO09(), FH_PWMO_SetStatus_PWMO10(), FH_PWMO_SetStatus_PWMO11(), FH_PWMO_SetStatus_PWMO12(), FH_PWMO_SetStatus_PWMO13(), FH_PWMO_SetStatus_PWMO14(), FH_PWMO_SetStatus_PWMO15(), FH_PWMO_SetStatus_PWMO16(), FH_PWMO_SetStatus_PWMO17(), FH_PWMO_SetStatus_PWMO18(), FH_PWMO_SetStatus_PWMO19(), FH_PWMO_SetStatus_PWMO20(), FH_PWMO_SetStatus_PWMO21(), FH_PWMO_SetStatus_PWMO22(), FH_PWMO_SetStatus_PWMO23(), FH_PWMO_SetStatus_PWMO24(), FH_PWMO_SetStatus_PWMO25(), FH_PWMO_SetStatus_PWMO26(), FH_PWMO_SetStatus_PWMO27(), FH_PWMO_SetStatus_PWMO28(), FH_PWMO_SetStatus_PWMO29(), FH_PWMO_SetStatus_PWMO30(), FH_PWMO_SetStatus_PWMO31(), FH_PWMO_SetStatus_PWMO32(), and NULL_PTR.
Referenced by FH_PWMO_ProcessCommand_SetStatus().