FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_AI/FH_AI.c File Reference
FH_AI.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_AI (Analog Input)
Functions in this file, handle RFCommunication (RobotFramework Communication) for all commands related to AI (Analog Input)
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/FH_AI.h"
#include "stdio.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../FH_Embedded/FH_Setup/FH_DeviceAddress/FH_DeviceAddress.h"
#include "../../../../FH_Embedded/FH_Setup/FH_RFCommunication/FH_RFCommunication.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/Init/Init_H/FH_AI_Init_H.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/Init/Init_C/FH_AI_Init_C.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/Init/Init_S/FH_AI_Init_S.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/GetStatus/GetStatus_H/FH_AI_GetStatus_H.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/GetStatus/GetStatus_C/FH_AI_GetStatus_C.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/GetStatus/GetStatus_S/FH_AI_GetStatus_S.h"
Functions
FH_ErrorInfo FH_AI_RFCommunication (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function is the basic function of handling RFCommunication (RobotFramework Communication) for all the Commands related to the Function AI (Analog Input)
This function is called from FH_RFCommunication()
FH_ErrorInfo FH_AI_ProcessCommand_Init (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function handles FH_AI_Commands_Init command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AI (Analog Input) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AI (Analog Input) according to the first parameter of the Data in the message frame.
FH_ErrorInfo FH_AI_ProcessCommand_GetStatus (FH_RFCommunication_Message *fh_RFCommunication_Message, uint32_t *FH_AI_Data)
This function handles FH_AI_Commands_GetStatus command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AI (Analog Input) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AI (Analog Input) according to the first parameter of the Data in the message frame.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_AI (Analog Input)
Functions in this file, handle RFCommunication (RobotFramework Communication) for all commands related to AI (Analog Input)
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AI.c.
Function Documentation
FH_AI_ProcessCommand_GetStatus()
FH_ErrorInfo FH_AI_ProcessCommand_GetStatus (FH_RFCommunication_Message * fh_RFCommunication_Message, uint32_t * FH_AI_Data)
This function handles FH_AI_Commands_GetStatus command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AI (Analog Input) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AI (Analog Input) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AI01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AI}    Command=${AI_Commands_GetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AI01 => It indicates the Analog Input 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AI => It is the function in the message frame
  AI_Commands_GetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 172 of file FH_AI.c.
References FH_ErrorInfo::error_code, FH_AI_GetStatus_C(), FH_AI_GetStatus_H(), FH_AI_GetStatus_S(), FH_AI_MaxPeripheralNumber, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_AI_RFCommunication().
FH_AI_ProcessCommand_Init()
FH_ErrorInfo FH_AI_ProcessCommand_Init (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function handles FH_AI_Commands_Init command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AI (Analog Input) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AI (Analog Input) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AI01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AI}    Command=${AI_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AI01 => It indicates the Analog Input 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AI => It is the function in the message frame
  AI_Commands_Init => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 119 of file FH_AI.c.
References FH_ErrorInfo::error_code, FH_AI_Init_C(), FH_AI_Init_H(), FH_AI_Init_S(), FH_AI_MaxPeripheralNumber, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_AI_RFCommunication().
FH_AI_RFCommunication()
FH_ErrorInfo FH_AI_RFCommunication (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function is the basic function of handling RFCommunication (RobotFramework Communication) for all the Commands related to the Function AI (Analog Input)
This function is called from FH_RFCommunication()
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 50 of file FH_AI.c.
References FH_Uint8Uint32::bytes, FH_ErrorInfo::error_code, FH_AI_Commands_GetStatus, FH_AI_Commands_Init, FH_AI_ProcessCommand_GetStatus(), FH_AI_ProcessCommand_Init(), FH_ResetErrorInfo(), FH_RFCommunication_DeviceAddress, fh_RFCommunication_Message, FH_RFCommunication_Send(), FH_RFCommunication_SendBuf, and FH_Uint8Uint32::value.
Referenced by FH_RFCommunication().