FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/GetStatus/GetStatus_S/FH_AI_GetStatus_S.c File Reference
FH_AI_GetStatus_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_AI (Analog Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AI (Analog Input), FH_AI_GetStatus_AI01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_AI/Cmd/GetStatus/GetStatus_S/FH_AI_GetStatus_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI01/FH_AI01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI02/FH_AI02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI03/FH_AI03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI04/FH_AI04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI05/FH_AI05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI06/FH_AI06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI07/FH_AI07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI08/FH_AI08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI09/FH_AI09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI10/FH_AI10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI11/FH_AI11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI12/FH_AI12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI13/FH_AI13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI14/FH_AI14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI15/FH_AI15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI16/FH_AI16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI17/FH_AI17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI18/FH_AI18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI19/FH_AI19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI20/FH_AI20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI21/FH_AI21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI22/FH_AI22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI23/FH_AI23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI24/FH_AI24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI25/FH_AI25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI26/FH_AI26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI27/FH_AI27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI28/FH_AI28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI29/FH_AI29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI30/FH_AI30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI31/FH_AI31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AI/FH_AI32/FH_AI32.h"
Functions
void FH_AI_GetStatus_S (FH_AI_GetStatus_FuncPtrModel *FH_AI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AI (Analog Input), FH_AI_GetStatus_AI01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_AI (Analog Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AI (Analog Input), FH_AI_GetStatus_AI01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AI_GetStatus_S.c.
Function Documentation
FH_AI_GetStatus_S()
void FH_AI_GetStatus_S (FH_AI_GetStatus_FuncPtrModel * FH_AI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AI (Analog Input), FH_AI_GetStatus_AI01-... to an array of function pointers.
Parameters
FH_AI_GetStatus_FuncPtr An array of function pointers with FH_AI_GetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_AI_GetStatus_S.c.
References FH_AI_GetStatus_AI01(), FH_AI_GetStatus_AI02(), FH_AI_GetStatus_AI03(), FH_AI_GetStatus_AI04(), FH_AI_GetStatus_AI05(), FH_AI_GetStatus_AI06(), FH_AI_GetStatus_AI07(), FH_AI_GetStatus_AI08(), FH_AI_GetStatus_AI09(), FH_AI_GetStatus_AI10(), FH_AI_GetStatus_AI11(), FH_AI_GetStatus_AI12(), FH_AI_GetStatus_AI13(), FH_AI_GetStatus_AI14(), FH_AI_GetStatus_AI15(), FH_AI_GetStatus_AI16(), FH_AI_GetStatus_AI17(), FH_AI_GetStatus_AI18(), FH_AI_GetStatus_AI19(), FH_AI_GetStatus_AI20(), FH_AI_GetStatus_AI21(), FH_AI_GetStatus_AI22(), FH_AI_GetStatus_AI23(), FH_AI_GetStatus_AI24(), FH_AI_GetStatus_AI25(), FH_AI_GetStatus_AI26(), FH_AI_GetStatus_AI27(), FH_AI_GetStatus_AI28(), FH_AI_GetStatus_AI29(), FH_AI_GetStatus_AI30(), FH_AI_GetStatus_AI31(), FH_AI_GetStatus_AI32(), FH_AI_MaxPeripheralNumber, and NULL_PTR.
Referenced by FH_AI_ProcessCommand_GetStatus().