FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO08/FH_PWMO08.c File Reference
FH_PWMO08.c File Reference
File Map:
FH_Functions, Section FH_PWMO (PWM Output), Peripheral FH_PWMO08 (PWM Output 08)
(The PWMO08 (PWM Output 08) could be any interested PWM Output of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO08/FH_PWMO08.h"
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_PWMO/FH_PWMO.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GlobalTimerCount/FH_GlobalTimerCount.h"
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
Functions
FH_ErrorInfo FH_PWMO_Init_PWMO08 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function initializes the PWM Output 08
The PWM Output 08 could be any interested PWM Output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested PWM Output here.
FH_ErrorInfo FH_PWMO_SetStatus_PWMO08 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function sets the PWM Output 08
The PWM Output 08 could be any interested PWM Output of the micro-controller on which FH source code is ported
FH user should call the set function of the interested PWM Output here.
Detailed Description
File Map:
FH_Functions, Section FH_PWMO (PWM Output), Peripheral FH_PWMO08 (PWM Output 08)
(The PWMO08 (PWM Output 08) could be any interested PWM Output of the micro-controller on which FH source code is ported)
Note
To have a clean code, FH user should have the implementation of the initialization and set function of of the PWM Output 08 in a separate c file
Then FH user should include the header file (.h) of the related source file (.c) here
This header file shall include the following items:
The declaration of the initialization function of the PWM Output 08
The declaration of the set function of the PWM Output 08
Attention
There are a total number of 3 attentions (FH user defined code) in this file where FH user shall insert some code
Other parts could be left intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_PWMO08.c.
Function Documentation
FH_PWMO_Init_PWMO08()
FH_ErrorInfo FH_PWMO_Init_PWMO08 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function initializes the PWM Output 08
The PWM Output 08 could be any interested PWM Output of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested PWM Output here.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${PWMO08}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_PWMO}    Command=${PWMO_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  PWMO08 => It indicates the PWM Output 08
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_PWMO => It is the function in the message frame
  PWMO_Commands_Init => It is the command of the function in the message frame
Warning
To be able to set or reset the PWM Output 08 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_PWMO_SetStatus_PWMO08 function from RobotFramework, this function shall be invoked in order to initialize the PWM Output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 78 of file FH_PWMO08.c.
References FH_ResetErrorInfo().
Referenced by FH_PWMO_Init_S().
FH_PWMO_SetStatus_PWMO08()
FH_ErrorInfo FH_PWMO_SetStatus_PWMO08 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function sets the PWM Output 08
The PWM Output 08 could be any interested PWM Output of the micro-controller on which FH source code is ported
FH user should call the set function of the interested PWM Output here.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${PWMO08}    00    00    00    F0    32
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_PWMO}    Command=${PWMO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  PWMO08 => It indicates the PWM Output 08
  00    00    00    F0 => Example data as PWM frequency (0x000000F0) to be set through the <b>PWM Output 08</b>\n
  32 => Example data as PWM duty cycle (0x32 => as 50% duty cycle) to be set through the <b>PWM Output 08</b>\n
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_PWMO => It is the function in the message frame
  PWMO_Commands_SetStatus => It is the command of the function in the message frame
Warning
To be able to set the PWM Output 08 of the micro-controller on which FH source code is ported, the FH_PWMO_Init_PWMO08 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_PWMO_SetStatus_PWMO08 function from RobotFramework, FH_PWMO_Init_PWMO08 function shall be invoked in order to initialize the PWM Output
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 131 of file FH_PWMO08.c.
References FH_ResetErrorInfo().
Referenced by FH_PWMO_SetStatus_S().