FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_AO/Cmd/SetStatus/SetStatus_S/FH_AO_SetStatus_S.c File Reference
FH_AO_SetStatus_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_SetStatus_AO01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_AO/Cmd/SetStatus/SetStatus_S/FH_AO_SetStatus_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO01/FH_AO01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO02/FH_AO02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO03/FH_AO03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO04/FH_AO04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO05/FH_AO05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO06/FH_AO06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO07/FH_AO07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO08/FH_AO08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO09/FH_AO09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO10/FH_AO10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO11/FH_AO11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO12/FH_AO12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO13/FH_AO13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO14/FH_AO14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO15/FH_AO15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO16/FH_AO16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO17/FH_AO17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO18/FH_AO18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO19/FH_AO19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO20/FH_AO20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO21/FH_AO21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO22/FH_AO22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO23/FH_AO23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO24/FH_AO24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO25/FH_AO25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO26/FH_AO26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO27/FH_AO27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO28/FH_AO28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO29/FH_AO29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO30/FH_AO30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO31/FH_AO31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_AO/FH_AO32/FH_AO32.h"
Functions
void FH_AO_SetStatus_S (FH_AO_SetStatus_FuncPtrModel *FH_AO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_SetStatus_AO01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_SetStatus_AO01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AO_SetStatus_S.c.
Function Documentation
FH_AO_SetStatus_S()
void FH_AO_SetStatus_S (FH_AO_SetStatus_FuncPtrModel * FH_AO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_AO (Analog Output), FH_AO_SetStatus_AO01-... to an array of function pointers.
Parameters
FH_AO_SetStatus_FuncPtr An array of function pointers with FH_AO_SetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_AO_SetStatus_S.c.
References FH_AO_MaxPeripheralNumber, FH_AO_SetStatus_AO01(), FH_AO_SetStatus_AO02(), FH_AO_SetStatus_AO03(), FH_AO_SetStatus_AO04(), FH_AO_SetStatus_AO05(), FH_AO_SetStatus_AO06(), FH_AO_SetStatus_AO07(), FH_AO_SetStatus_AO08(), FH_AO_SetStatus_AO09(), FH_AO_SetStatus_AO10(), FH_AO_SetStatus_AO11(), FH_AO_SetStatus_AO12(), FH_AO_SetStatus_AO13(), FH_AO_SetStatus_AO14(), FH_AO_SetStatus_AO15(), FH_AO_SetStatus_AO16(), FH_AO_SetStatus_AO17(), FH_AO_SetStatus_AO18(), FH_AO_SetStatus_AO19(), FH_AO_SetStatus_AO20(), FH_AO_SetStatus_AO21(), FH_AO_SetStatus_AO22(), FH_AO_SetStatus_AO23(), FH_AO_SetStatus_AO24(), FH_AO_SetStatus_AO25(), FH_AO_SetStatus_AO26(), FH_AO_SetStatus_AO27(), FH_AO_SetStatus_AO28(), FH_AO_SetStatus_AO29(), FH_AO_SetStatus_AO30(), FH_AO_SetStatus_AO31(), FH_AO_SetStatus_AO32(), and NULL_PTR.
Referenced by FH_AO_ProcessCommand_SetStatus().