FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_UART/Cmd/SSD16/SSD16_S/FH_UART_SSD16_S.c File Reference
FH_UART_SSD16_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_UART (Digital Output), Cmd (Command), SSD16, SSD16_S (Set Shared Data 16 Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_UART (UART), FH_UART_SSD16_UART01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_UART/Cmd/SSD16/SSD16_S/FH_UART_SSD16_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART01/FH_UART01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART02/FH_UART02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART03/FH_UART03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_UART/FH_UART04/FH_UART04.h"
Functions
void FH_UART_SSD16_S (FH_UART_SSD16_FuncPtrModel *FH_UART_SSD16_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_UART (UART), FH_UART_SSD16_UART01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_UART (Digital Output), Cmd (Command), SSD16, SSD16_S (Set Shared Data 16 Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_UART (UART), FH_UART_SSD16_UART01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_UART_SSD16_S.c.
Function Documentation
FH_UART_SSD16_S()
void FH_UART_SSD16_S (FH_UART_SSD16_FuncPtrModel * FH_UART_SSD16_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_UART (UART), FH_UART_SSD16_UART01-... to an array of function pointers.
Parameters
FH_UART_SSD16_FuncPtr An array of function pointers with FH_UART_SSD16_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 64 of file FH_UART_SSD16_S.c.
References FH_UART_MaxPeripheralNumber, FH_UART_SSD16_UART01(), FH_UART_SSD16_UART02(), FH_UART_SSD16_UART03(), FH_UART_SSD16_UART04(), and NULL_PTR.
Referenced by FH_UART_ProcessCommand_SSD16().