FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_General/FH_ErrorInfo/FH_ErrorInfo.c File Reference
FH_ErrorInfo.c File Reference
File Map:
FH_Root, Section FH_General, FH_ErrorInfo
To monitor different possible errors in different parts of the code, FH_ErrorInfo structure is utilized
The FH_ErrorInfo is a structure where error_code and error_message are the members
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_ErrorInfo/FH_ErrorInfo.h"
Functions
void FH_ResetErrorInfo (FH_ErrorInfo *fh_ErrorInfo)
This function initializes the error information before calling different functions
The FH_ErrorInfo is a structure where error_code and error_message are the members
There are different error codes available which are all defined in FH_ErrorInfo.h
This function initializes the error code with FH_ERROR_NoInfo and the error message with ""
Detailed Description
File Map:
FH_Root, Section FH_General, FH_ErrorInfo
To monitor different possible errors in different parts of the code, FH_ErrorInfo structure is utilized
The FH_ErrorInfo is a structure where error_code and error_message are the members
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_ErrorInfo.c.
Function Documentation
FH_ResetErrorInfo()
void FH_ResetErrorInfo (FH_ErrorInfo * fh_ErrorInfo)
This function initializes the error information before calling different functions
The FH_ErrorInfo is a structure where error_code and error_message are the members
There are different error codes available which are all defined in FH_ErrorInfo.h
This function initializes the error code with FH_ERROR_NoInfo and the error message with ""
Parameters
fh_ErrorInfo it is a pointer to the structure FH_ErrorInfo
Returns
None
Note
In order not to initialize the fh_ErrorInfo repeatedly (whenever needed), this function is utilized
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 41 of file FH_ErrorInfo.c.
References FH_ERROR_NoInfo.
Referenced by FH_AI_GetStatus_AI01(), FH_AI_GetStatus_AI02(), FH_AI_GetStatus_AI03(), FH_AI_GetStatus_AI04(), FH_AI_GetStatus_AI05(), FH_AI_GetStatus_AI06(), FH_AI_GetStatus_AI07(), FH_AI_GetStatus_AI08(), FH_AI_GetStatus_AI09(), FH_AI_GetStatus_AI10(), FH_AI_GetStatus_AI11(), FH_AI_GetStatus_AI12(), FH_AI_GetStatus_AI13(), FH_AI_GetStatus_AI14(), FH_AI_GetStatus_AI15(), FH_AI_GetStatus_AI16(), FH_AI_GetStatus_AI17(), FH_AI_GetStatus_AI18(), FH_AI_GetStatus_AI19(), FH_AI_GetStatus_AI20(), FH_AI_GetStatus_AI21(), FH_AI_GetStatus_AI22(), FH_AI_GetStatus_AI23(), FH_AI_GetStatus_AI24(), FH_AI_GetStatus_AI25(), FH_AI_GetStatus_AI26(), FH_AI_GetStatus_AI27(), FH_AI_GetStatus_AI28(), FH_AI_GetStatus_AI29(), FH_AI_GetStatus_AI30(), FH_AI_GetStatus_AI31(), FH_AI_GetStatus_AI32(), FH_AI_GetStatus_C(), FH_AI_GetStatus_H(), FH_AI_Init_AI01(), FH_AI_Init_AI02(), FH_AI_Init_AI03(), FH_AI_Init_AI04(), FH_AI_Init_AI05(), FH_AI_Init_AI06(), FH_AI_Init_AI07(), FH_AI_Init_AI08(), FH_AI_Init_AI09(), FH_AI_Init_AI10(), FH_AI_Init_AI11(), FH_AI_Init_AI12(), FH_AI_Init_AI13(), FH_AI_Init_AI14(), FH_AI_Init_AI15(), FH_AI_Init_AI16(), FH_AI_Init_AI17(), FH_AI_Init_AI18(), FH_AI_Init_AI19(), FH_AI_Init_AI20(), FH_AI_Init_AI21(), FH_AI_Init_AI22(), FH_AI_Init_AI23(), FH_AI_Init_AI24(), FH_AI_Init_AI25(), FH_AI_Init_AI26(), FH_AI_Init_AI27(), FH_AI_Init_AI28(), FH_AI_Init_AI29(), FH_AI_Init_AI30(), FH_AI_Init_AI31(), FH_AI_Init_AI32(), FH_AI_Init_C(), FH_AI_Init_H(), FH_AI_ProcessCommand_GetStatus(), FH_AI_ProcessCommand_Init(), FH_AI_RFCommunication(), FH_AO_Init_AO01(), FH_AO_Init_AO02(), FH_AO_Init_AO03(), FH_AO_Init_AO04(), FH_AO_Init_AO05(), FH_AO_Init_AO06(), FH_AO_Init_AO07(), FH_AO_Init_AO08(), FH_AO_Init_AO09(), FH_AO_Init_AO10(), FH_AO_Init_AO11(), FH_AO_Init_AO12(), FH_AO_Init_AO13(), FH_AO_Init_AO14(), FH_AO_Init_AO15(), FH_AO_Init_AO16(), FH_AO_Init_AO17(), FH_AO_Init_AO18(), FH_AO_Init_AO19(), FH_AO_Init_AO20(), FH_AO_Init_AO21(), FH_AO_Init_AO22(), FH_AO_Init_AO23(), FH_AO_Init_AO24(), FH_AO_Init_AO25(), FH_AO_Init_AO26(), FH_AO_Init_AO27(), FH_AO_Init_AO28(), FH_AO_Init_AO29(), FH_AO_Init_AO30(), FH_AO_Init_AO31(), FH_AO_Init_AO32(), FH_AO_Init_C(), FH_AO_Init_H(), FH_AO_ProcessCommand_Init(), FH_AO_ProcessCommand_SetStatus(), FH_AO_RFCommunication(), FH_AO_SetStatus_AO01(), FH_AO_SetStatus_AO02(), FH_AO_SetStatus_AO03(), FH_AO_SetStatus_AO04(), FH_AO_SetStatus_AO05(), FH_AO_SetStatus_AO06(), FH_AO_SetStatus_AO07(), FH_AO_SetStatus_AO08(), FH_AO_SetStatus_AO09(), FH_AO_SetStatus_AO10(), FH_AO_SetStatus_AO11(), FH_AO_SetStatus_AO12(), FH_AO_SetStatus_AO13(), FH_AO_SetStatus_AO14(), FH_AO_SetStatus_AO15(), FH_AO_SetStatus_AO16(), FH_AO_SetStatus_AO17(), FH_AO_SetStatus_AO18(), FH_AO_SetStatus_AO19(), FH_AO_SetStatus_AO20(), FH_AO_SetStatus_AO21(), FH_AO_SetStatus_AO22(), FH_AO_SetStatus_AO23(), FH_AO_SetStatus_AO24(), FH_AO_SetStatus_AO25(), FH_AO_SetStatus_AO26(), FH_AO_SetStatus_AO27(), FH_AO_SetStatus_AO28(), FH_AO_SetStatus_AO29(), FH_AO_SetStatus_AO30(), FH_AO_SetStatus_AO31(), FH_AO_SetStatus_AO32(), FH_AO_SetStatus_C(), FH_AO_SetStatus_H(), FH_CAN_GSD16_C(), FH_CAN_GSD16_CAN01(), FH_CAN_GSD16_CAN02(), FH_CAN_GSD16_CAN03(), FH_CAN_GSD16_CAN04(), FH_CAN_GSD16_H(), FH_CAN_GSD32_C(), FH_CAN_GSD32_CAN01(), FH_CAN_GSD32_CAN02(), FH_CAN_GSD32_CAN03(), FH_CAN_GSD32_CAN04(), FH_CAN_GSD32_H(), FH_CAN_GSD8_C(), FH_CAN_GSD8_CAN01(), FH_CAN_GSD8_CAN02(), FH_CAN_GSD8_CAN03(), FH_CAN_GSD8_CAN04(), FH_CAN_GSD8_H(), FH_CAN_Init_C(), FH_CAN_Init_CAN01(), FH_CAN_Init_CAN02(), FH_CAN_Init_CAN03(), FH_CAN_Init_CAN04(), FH_CAN_Init_H(), FH_CAN_ProcessCommand_GSD16(), FH_CAN_ProcessCommand_GSD32(), FH_CAN_ProcessCommand_GSD8(), FH_CAN_ProcessCommand_Init(), FH_CAN_ProcessCommand_Receive(), FH_CAN_ProcessCommand_ReceiveW(), FH_CAN_ProcessCommand_ResetRB(), FH_CAN_ProcessCommand_Send(), FH_CAN_ProcessCommand_SSD16(), FH_CAN_ProcessCommand_SSD32(), FH_CAN_ProcessCommand_SSD8(), FH_CAN_Receive_C(), FH_CAN_Receive_CAN01(), FH_CAN_Receive_CAN02(), FH_CAN_Receive_CAN03(), FH_CAN_Receive_CAN04(), FH_CAN_Receive_H(), FH_CAN_ReceiveW_C(), FH_CAN_ReceiveW_CAN01(), FH_CAN_ReceiveW_CAN02(), FH_CAN_ReceiveW_CAN03(), FH_CAN_ReceiveW_CAN04(), FH_CAN_ReceiveW_H(), FH_CAN_ResetRB_C(), FH_CAN_ResetRB_CAN01(), FH_CAN_ResetRB_CAN02(), FH_CAN_ResetRB_CAN03(), FH_CAN_ResetRB_CAN04(), FH_CAN_ResetRB_H(), FH_CAN_RFCommunication(), FH_CAN_Send_C(), FH_CAN_Send_CAN01(), FH_CAN_Send_CAN02(), FH_CAN_Send_CAN03(), FH_CAN_Send_CAN04(), FH_CAN_Send_H(), FH_CAN_SSD16_C(), FH_CAN_SSD16_CAN01(), FH_CAN_SSD16_CAN02(), FH_CAN_SSD16_CAN03(), FH_CAN_SSD16_CAN04(), FH_CAN_SSD16_H(), FH_CAN_SSD32_C(), FH_CAN_SSD32_CAN01(), FH_CAN_SSD32_CAN02(), FH_CAN_SSD32_CAN03(), FH_CAN_SSD32_CAN04(), FH_CAN_SSD32_H(), FH_CAN_SSD8_C(), FH_CAN_SSD8_CAN01(), FH_CAN_SSD8_CAN02(), FH_CAN_SSD8_CAN03(), FH_CAN_SSD8_CAN04(), FH_CAN_SSD8_H(), FH_DI_GetStatus_C(), FH_DI_GetStatus_DI01(), FH_DI_GetStatus_DI02(), FH_DI_GetStatus_DI03(), FH_DI_GetStatus_DI04(), FH_DI_GetStatus_DI05(), FH_DI_GetStatus_DI06(), FH_DI_GetStatus_DI07(), FH_DI_GetStatus_DI08(), FH_DI_GetStatus_DI09(), FH_DI_GetStatus_DI10(), FH_DI_GetStatus_DI11(), FH_DI_GetStatus_DI12(), FH_DI_GetStatus_DI13(), FH_DI_GetStatus_DI14(), FH_DI_GetStatus_DI15(), FH_DI_GetStatus_DI16(), FH_DI_GetStatus_DI17(), FH_DI_GetStatus_DI18(), FH_DI_GetStatus_DI19(), FH_DI_GetStatus_DI20(), FH_DI_GetStatus_DI21(), FH_DI_GetStatus_DI22(), FH_DI_GetStatus_DI23(), FH_DI_GetStatus_DI24(), FH_DI_GetStatus_DI25(), FH_DI_GetStatus_DI26(), FH_DI_GetStatus_DI27(), FH_DI_GetStatus_DI28(), FH_DI_GetStatus_DI29(), FH_DI_GetStatus_DI30(), FH_DI_GetStatus_DI31(), FH_DI_GetStatus_DI32(), FH_DI_GetStatus_DI33(), FH_DI_GetStatus_DI34(), FH_DI_GetStatus_DI35(), FH_DI_GetStatus_DI36(), FH_DI_GetStatus_DI37(), FH_DI_GetStatus_DI38(), FH_DI_GetStatus_DI39(), FH_DI_GetStatus_DI40(), FH_DI_GetStatus_DI41(), FH_DI_GetStatus_DI42(), FH_DI_GetStatus_DI43(), FH_DI_GetStatus_DI44(), FH_DI_GetStatus_DI45(), FH_DI_GetStatus_DI46(), FH_DI_GetStatus_DI47(), FH_DI_GetStatus_DI48(), FH_DI_GetStatus_DI49(), FH_DI_GetStatus_DI50(), FH_DI_GetStatus_DI51(), FH_DI_GetStatus_DI52(), FH_DI_GetStatus_DI53(), FH_DI_GetStatus_DI54(), FH_DI_GetStatus_DI55(), FH_DI_GetStatus_DI56(), FH_DI_GetStatus_DI57(), FH_DI_GetStatus_DI58(), FH_DI_GetStatus_DI59(), FH_DI_GetStatus_DI60(), FH_DI_GetStatus_DI61(), FH_DI_GetStatus_DI62(), FH_DI_GetStatus_DI63(), FH_DI_GetStatus_DI64(), FH_DI_GetStatus_H(), FH_DI_GetStatusMULTI_C(), FH_DI_GetStatusMULTI_H(), FH_DI_Init_C(), FH_DI_Init_DI01(), FH_DI_Init_DI02(), FH_DI_Init_DI03(), FH_DI_Init_DI04(), FH_DI_Init_DI05(), FH_DI_Init_DI06(), FH_DI_Init_DI07(), FH_DI_Init_DI08(), FH_DI_Init_DI09(), FH_DI_Init_DI10(), FH_DI_Init_DI11(), FH_DI_Init_DI12(), FH_DI_Init_DI13(), FH_DI_Init_DI14(), FH_DI_Init_DI15(), FH_DI_Init_DI16(), FH_DI_Init_DI17(), FH_DI_Init_DI18(), FH_DI_Init_DI19(), FH_DI_Init_DI20(), FH_DI_Init_DI21(), FH_DI_Init_DI22(), FH_DI_Init_DI23(), FH_DI_Init_DI24(), FH_DI_Init_DI25(), FH_DI_Init_DI26(), FH_DI_Init_DI27(), FH_DI_Init_DI28(), FH_DI_Init_DI29(), FH_DI_Init_DI30(), FH_DI_Init_DI31(), FH_DI_Init_DI32(), FH_DI_Init_DI33(), FH_DI_Init_DI34(), FH_DI_Init_DI35(), FH_DI_Init_DI36(), FH_DI_Init_DI37(), FH_DI_Init_DI38(), FH_DI_Init_DI39(), FH_DI_Init_DI40(), FH_DI_Init_DI41(), FH_DI_Init_DI42(), FH_DI_Init_DI43(), FH_DI_Init_DI44(), FH_DI_Init_DI45(), FH_DI_Init_DI46(), FH_DI_Init_DI47(), FH_DI_Init_DI48(), FH_DI_Init_DI49(), FH_DI_Init_DI50(), FH_DI_Init_DI51(), FH_DI_Init_DI52(), FH_DI_Init_DI53(), FH_DI_Init_DI54(), FH_DI_Init_DI55(), FH_DI_Init_DI56(), FH_DI_Init_DI57(), FH_DI_Init_DI58(), FH_DI_Init_DI59(), FH_DI_Init_DI60(), FH_DI_Init_DI61(), FH_DI_Init_DI62(), FH_DI_Init_DI63(), FH_DI_Init_DI64(), FH_DI_Init_H(), FH_DI_InitMULTI_C(), FH_DI_InitMULTI_H(), FH_DI_ProcessCommand_GetStatus(), FH_DI_ProcessCommand_GetStatusMULTI(), FH_DI_ProcessCommand_Init(), FH_DI_ProcessCommand_InitMULTI(), FH_DI_RFCommunication(), FH_DO_Init_C(), FH_DO_Init_DO01(), FH_DO_Init_DO02(), FH_DO_Init_DO03(), FH_DO_Init_DO04(), FH_DO_Init_DO05(), FH_DO_Init_DO06(), FH_DO_Init_DO07(), FH_DO_Init_DO08(), FH_DO_Init_DO09(), FH_DO_Init_DO10(), FH_DO_Init_DO11(), FH_DO_Init_DO12(), FH_DO_Init_DO13(), FH_DO_Init_DO14(), FH_DO_Init_DO15(), FH_DO_Init_DO16(), FH_DO_Init_DO17(), FH_DO_Init_DO18(), FH_DO_Init_DO19(), FH_DO_Init_DO20(), FH_DO_Init_DO21(), FH_DO_Init_DO22(), FH_DO_Init_DO23(), FH_DO_Init_DO24(), FH_DO_Init_DO25(), FH_DO_Init_DO26(), FH_DO_Init_DO27(), FH_DO_Init_DO28(), FH_DO_Init_DO29(), FH_DO_Init_DO30(), FH_DO_Init_DO31(), FH_DO_Init_DO32(), FH_DO_Init_DO33(), FH_DO_Init_DO34(), FH_DO_Init_DO35(), FH_DO_Init_DO36(), FH_DO_Init_DO37(), FH_DO_Init_DO38(), FH_DO_Init_DO39(), FH_DO_Init_DO40(), FH_DO_Init_DO41(), FH_DO_Init_DO42(), FH_DO_Init_DO43(), FH_DO_Init_DO44(), FH_DO_Init_DO45(), FH_DO_Init_DO46(), FH_DO_Init_DO47(), FH_DO_Init_DO48(), FH_DO_Init_DO49(), FH_DO_Init_DO50(), FH_DO_Init_DO51(), FH_DO_Init_DO52(), FH_DO_Init_DO53(), FH_DO_Init_DO54(), FH_DO_Init_DO55(), FH_DO_Init_DO56(), FH_DO_Init_DO57(), FH_DO_Init_DO58(), FH_DO_Init_DO59(), FH_DO_Init_DO60(), FH_DO_Init_DO61(), FH_DO_Init_DO62(), FH_DO_Init_DO63(), FH_DO_Init_DO64(), FH_DO_Init_H(), FH_DO_InitMULTI_C(), FH_DO_InitMULTI_H(), FH_DO_ProcessCommand_Init(), FH_DO_ProcessCommand_InitMULTI(), FH_DO_ProcessCommand_SetStatus(), FH_DO_ProcessCommand_SetStatusMULTI(), FH_DO_RFCommunication(), FH_DO_SetStatus_C(), FH_DO_SetStatus_DO01(), FH_DO_SetStatus_DO02(), FH_DO_SetStatus_DO03(), FH_DO_SetStatus_DO04(), FH_DO_SetStatus_DO05(), FH_DO_SetStatus_DO06(), FH_DO_SetStatus_DO07(), FH_DO_SetStatus_DO08(), FH_DO_SetStatus_DO09(), FH_DO_SetStatus_DO10(), FH_DO_SetStatus_DO11(), FH_DO_SetStatus_DO12(), FH_DO_SetStatus_DO13(), FH_DO_SetStatus_DO14(), FH_DO_SetStatus_DO15(), FH_DO_SetStatus_DO16(), FH_DO_SetStatus_DO17(), FH_DO_SetStatus_DO18(), FH_DO_SetStatus_DO19(), FH_DO_SetStatus_DO20(), FH_DO_SetStatus_DO21(), FH_DO_SetStatus_DO22(), FH_DO_SetStatus_DO23(), FH_DO_SetStatus_DO24(), FH_DO_SetStatus_DO25(), FH_DO_SetStatus_DO26(), FH_DO_SetStatus_DO27(), FH_DO_SetStatus_DO28(), FH_DO_SetStatus_DO29(), FH_DO_SetStatus_DO30(), FH_DO_SetStatus_DO31(), FH_DO_SetStatus_DO32(), FH_DO_SetStatus_DO33(), FH_DO_SetStatus_DO34(), FH_DO_SetStatus_DO35(), FH_DO_SetStatus_DO36(), FH_DO_SetStatus_DO37(), FH_DO_SetStatus_DO38(), FH_DO_SetStatus_DO39(), FH_DO_SetStatus_DO40(), FH_DO_SetStatus_DO41(), FH_DO_SetStatus_DO42(), FH_DO_SetStatus_DO43(), FH_DO_SetStatus_DO44(), FH_DO_SetStatus_DO45(), FH_DO_SetStatus_DO46(), FH_DO_SetStatus_DO47(), FH_DO_SetStatus_DO48(), FH_DO_SetStatus_DO49(), FH_DO_SetStatus_DO50(), FH_DO_SetStatus_DO51(), FH_DO_SetStatus_DO52(), FH_DO_SetStatus_DO53(), FH_DO_SetStatus_DO54(), FH_DO_SetStatus_DO55(), FH_DO_SetStatus_DO56(), FH_DO_SetStatus_DO57(), FH_DO_SetStatus_DO58(), FH_DO_SetStatus_DO59(), FH_DO_SetStatus_DO60(), FH_DO_SetStatus_DO61(), FH_DO_SetStatus_DO62(), FH_DO_SetStatus_DO63(), FH_DO_SetStatus_DO64(), FH_DO_SetStatus_H(), FH_DO_SetStatusMULTI_C(), FH_DO_SetStatusMULTI_H(), FH_PWMI_GetStatus_C(), FH_PWMI_GetStatus_H(), FH_PWMI_GetStatus_PWMI01(), FH_PWMI_GetStatus_PWMI02(), FH_PWMI_GetStatus_PWMI03(), FH_PWMI_GetStatus_PWMI04(), FH_PWMI_GetStatus_PWMI05(), FH_PWMI_GetStatus_PWMI06(), FH_PWMI_GetStatus_PWMI07(), FH_PWMI_GetStatus_PWMI08(), FH_PWMI_GetStatus_PWMI09(), FH_PWMI_GetStatus_PWMI10(), FH_PWMI_GetStatus_PWMI11(), FH_PWMI_GetStatus_PWMI12(), FH_PWMI_GetStatus_PWMI13(), FH_PWMI_GetStatus_PWMI14(), FH_PWMI_GetStatus_PWMI15(), FH_PWMI_GetStatus_PWMI16(), FH_PWMI_GetStatus_PWMI17(), FH_PWMI_GetStatus_PWMI18(), FH_PWMI_GetStatus_PWMI19(), FH_PWMI_GetStatus_PWMI20(), FH_PWMI_GetStatus_PWMI21(), FH_PWMI_GetStatus_PWMI22(), FH_PWMI_GetStatus_PWMI23(), FH_PWMI_GetStatus_PWMI24(), FH_PWMI_GetStatus_PWMI25(), FH_PWMI_GetStatus_PWMI26(), FH_PWMI_GetStatus_PWMI27(), FH_PWMI_GetStatus_PWMI28(), FH_PWMI_GetStatus_PWMI29(), FH_PWMI_GetStatus_PWMI30(), FH_PWMI_GetStatus_PWMI31(), FH_PWMI_GetStatus_PWMI32(), FH_PWMI_Init_C(), FH_PWMI_Init_H(), FH_PWMI_Init_PWMI01(), FH_PWMI_Init_PWMI02(), FH_PWMI_Init_PWMI03(), FH_PWMI_Init_PWMI04(), FH_PWMI_Init_PWMI05(), FH_PWMI_Init_PWMI06(), FH_PWMI_Init_PWMI07(), FH_PWMI_Init_PWMI08(), FH_PWMI_Init_PWMI09(), FH_PWMI_Init_PWMI10(), FH_PWMI_Init_PWMI11(), FH_PWMI_Init_PWMI12(), FH_PWMI_Init_PWMI13(), FH_PWMI_Init_PWMI14(), FH_PWMI_Init_PWMI15(), FH_PWMI_Init_PWMI16(), FH_PWMI_Init_PWMI17(), FH_PWMI_Init_PWMI18(), FH_PWMI_Init_PWMI19(), FH_PWMI_Init_PWMI20(), FH_PWMI_Init_PWMI21(), FH_PWMI_Init_PWMI22(), FH_PWMI_Init_PWMI23(), FH_PWMI_Init_PWMI24(), FH_PWMI_Init_PWMI25(), FH_PWMI_Init_PWMI26(), FH_PWMI_Init_PWMI27(), FH_PWMI_Init_PWMI28(), FH_PWMI_Init_PWMI29(), FH_PWMI_Init_PWMI30(), FH_PWMI_Init_PWMI31(), FH_PWMI_Init_PWMI32(), FH_PWMI_ProcessCommand_GetStatus(), FH_PWMI_ProcessCommand_Init(), FH_PWMI_RFCommunication(), FH_PWMO_Init_C(), FH_PWMO_Init_H(), FH_PWMO_Init_PWMO01(), FH_PWMO_Init_PWMO02(), FH_PWMO_Init_PWMO03(), FH_PWMO_Init_PWMO04(), FH_PWMO_Init_PWMO05(), FH_PWMO_Init_PWMO06(), FH_PWMO_Init_PWMO07(), FH_PWMO_Init_PWMO08(), FH_PWMO_Init_PWMO09(), FH_PWMO_Init_PWMO10(), FH_PWMO_Init_PWMO11(), FH_PWMO_Init_PWMO12(), FH_PWMO_Init_PWMO13(), FH_PWMO_Init_PWMO14(), FH_PWMO_Init_PWMO15(), FH_PWMO_Init_PWMO16(), FH_PWMO_Init_PWMO17(), FH_PWMO_Init_PWMO18(), FH_PWMO_Init_PWMO19(), FH_PWMO_Init_PWMO20(), FH_PWMO_Init_PWMO21(), FH_PWMO_Init_PWMO22(), FH_PWMO_Init_PWMO23(), FH_PWMO_Init_PWMO24(), FH_PWMO_Init_PWMO25(), FH_PWMO_Init_PWMO26(), FH_PWMO_Init_PWMO27(), FH_PWMO_Init_PWMO28(), FH_PWMO_Init_PWMO29(), FH_PWMO_Init_PWMO30(), FH_PWMO_Init_PWMO31(), FH_PWMO_Init_PWMO32(), FH_PWMO_ProcessCommand_Init(), FH_PWMO_ProcessCommand_SetStatus(), FH_PWMO_RFCommunication(), FH_PWMO_SetStatus_C(), FH_PWMO_SetStatus_H(), FH_PWMO_SetStatus_PWMO01(), FH_PWMO_SetStatus_PWMO02(), FH_PWMO_SetStatus_PWMO03(), FH_PWMO_SetStatus_PWMO04(), FH_PWMO_SetStatus_PWMO05(), FH_PWMO_SetStatus_PWMO06(), FH_PWMO_SetStatus_PWMO07(), FH_PWMO_SetStatus_PWMO08(), FH_PWMO_SetStatus_PWMO09(), FH_PWMO_SetStatus_PWMO10(), FH_PWMO_SetStatus_PWMO11(), FH_PWMO_SetStatus_PWMO12(), FH_PWMO_SetStatus_PWMO13(), FH_PWMO_SetStatus_PWMO14(), FH_PWMO_SetStatus_PWMO15(), FH_PWMO_SetStatus_PWMO16(), FH_PWMO_SetStatus_PWMO17(), FH_PWMO_SetStatus_PWMO18(), FH_PWMO_SetStatus_PWMO19(), FH_PWMO_SetStatus_PWMO20(), FH_PWMO_SetStatus_PWMO21(), FH_PWMO_SetStatus_PWMO22(), FH_PWMO_SetStatus_PWMO23(), FH_PWMO_SetStatus_PWMO24(), FH_PWMO_SetStatus_PWMO25(), FH_PWMO_SetStatus_PWMO26(), FH_PWMO_SetStatus_PWMO27(), FH_PWMO_SetStatus_PWMO28(), FH_PWMO_SetStatus_PWMO29(), FH_PWMO_SetStatus_PWMO30(), FH_PWMO_SetStatus_PWMO31(), FH_PWMO_SetStatus_PWMO32(), FH_RFCommunication(), FH_RFCommunication_Init(), FH_RFCommunication_Receive(), FH_RFCommunication_Send(), FH_UART_GSD16_C(), FH_UART_GSD16_H(), FH_UART_GSD16_UART01(), FH_UART_GSD16_UART02(), FH_UART_GSD16_UART03(), FH_UART_GSD16_UART04(), FH_UART_GSD32_C(), FH_UART_GSD32_H(), FH_UART_GSD32_UART01(), FH_UART_GSD32_UART02(), FH_UART_GSD32_UART03(), FH_UART_GSD32_UART04(), FH_UART_GSD8_C(), FH_UART_GSD8_H(), FH_UART_GSD8_UART01(), FH_UART_GSD8_UART02(), FH_UART_GSD8_UART03(), FH_UART_GSD8_UART04(), FH_UART_Init_C(), FH_UART_Init_H(), FH_UART_Init_UART01(), FH_UART_Init_UART02(), FH_UART_Init_UART03(), FH_UART_Init_UART04(), FH_UART_ProcessCommand_GSD16(), FH_UART_ProcessCommand_GSD32(), FH_UART_ProcessCommand_GSD8(), FH_UART_ProcessCommand_Init(), FH_UART_ProcessCommand_Receive(), FH_UART_ProcessCommand_ReceiveW(), FH_UART_ProcessCommand_ResetRB(), FH_UART_ProcessCommand_Send(), FH_UART_ProcessCommand_SSD16(), FH_UART_ProcessCommand_SSD32(), FH_UART_ProcessCommand_SSD8(), FH_UART_Receive_C(), FH_UART_Receive_H(), FH_UART_Receive_UART01(), FH_UART_Receive_UART02(), FH_UART_Receive_UART03(), FH_UART_Receive_UART04(), FH_UART_ReceiveW_C(), FH_UART_ReceiveW_H(), FH_UART_ReceiveW_UART01(), FH_UART_ReceiveW_UART02(), FH_UART_ReceiveW_UART03(), FH_UART_ReceiveW_UART04(), FH_UART_ResetRB_C(), FH_UART_ResetRB_H(), FH_UART_ResetRB_UART01(), FH_UART_ResetRB_UART02(), FH_UART_ResetRB_UART03(), FH_UART_ResetRB_UART04(), FH_UART_RFCommunication(), FH_UART_Send_C(), FH_UART_Send_H(), FH_UART_Send_UART01(), FH_UART_Send_UART02(), FH_UART_Send_UART03(), FH_UART_Send_UART04(), FH_UART_SSD16_C(), FH_UART_SSD16_H(), FH_UART_SSD16_UART01(), FH_UART_SSD16_UART02(), FH_UART_SSD16_UART03(), FH_UART_SSD16_UART04(), FH_UART_SSD32_C(), FH_UART_SSD32_H(), FH_UART_SSD32_UART01(), FH_UART_SSD32_UART02(), FH_UART_SSD32_UART03(), FH_UART_SSD32_UART04(), FH_UART_SSD8_C(), FH_UART_SSD8_H(), FH_UART_SSD8_UART01(), FH_UART_SSD8_UART02(), FH_UART_SSD8_UART03(), and FH_UART_SSD8_UART04().