FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH/FH_Root/FH_Perif/FH_DO/Cmd/SetStatus/SetStatus_R/FH_DO_SetStatus_R.c File Reference
FH_DO_SetStatus_R.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_R (SetStatus Run)
Functions in this file, Call the related function in FH_Functions, Section FH_DO (Digital Output)
#include "FH_DO_SetStatus_R.h"
#include "../../../../../../FH_Setup/FH_DeviceAddress/FH_DeviceAddress.h"
#include "../../../../../FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
Functions
FH_ErrorInfo FH_DO_SetStatus_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, FH_DO_SetStatus_FuncPtrModel *FH_DO_SetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DO (Digital Output) according to the first parameter of the Data in the message frame.
FH_ErrorInfo FH_DO_SetStatusMULTI_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, FH_DO_SetStatus_FuncPtrModel *FH_DO_SetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DO (Digital Output) according to the 16 first parameters of the Data in the message frame
(The first 8 bytes as mask resemble 64 bits and each bit resembles 1 DO (Digital Output) and if the bit is 1, the related DO (Digital Output) function will be called)
(The second 8 bytes as data resemble 64 bits and each bit resembles status of 1 DO (Digital Output) as 1 or 0 of the corresponding bit in the first 8 bytes)
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_R (SetStatus Run)
Functions in this file, Call the related function in FH_Functions, Section FH_DO (Digital Output)
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DO_SetStatus_R.c.
Function Documentation
FH_DO_SetStatus_R_Start()
FH_ErrorInfo FH_DO_SetStatus_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, FH_DO_SetStatus_FuncPtrModel * FH_DO_SetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DO (Digital Output) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DO_SetStatus_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    DO01    DO_Set
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO01 => It indicates the Digital Output 01
  DO_Set => It indicates the Digital Output 01 shall be Set (DO_Reset indicates the Digital Output 01 shall be Reset)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 58 of file FH_DO_SetStatus_R.c.
References FH_ErrorInfo::error_code, FH_DO_MaxPeripheralNumber, FH_ERROR_CommandData, FH_ERROR_Functions, FH_ERROR_NoInfo, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DO_ProcessCommand_SetStatus().
FH_DO_SetStatusMULTI_R_Start()
FH_ErrorInfo FH_DO_SetStatusMULTI_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, FH_DO_SetStatus_FuncPtrModel * FH_DO_SetStatus_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DO (Digital Output) according to the 16 first parameters of the Data in the message frame
(The first 8 bytes as mask resemble 64 bits and each bit resembles 1 DO (Digital Output) and if the bit is 1, the related DO (Digital Output) function will be called)
(The second 8 bytes as data resemble 64 bits and each bit resembles status of 1 DO (Digital Output) as 1 or 0 of the corresponding bit in the first 8 bytes)
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DO_SetStatus_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    FF    FF    FF    FF    FF    FF    FF    FF    01    02    03    04    05    06    07    08
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatusMULTI}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  FF    FF    FF    FF    FF    FF    FF    FF => Example data as the first 8 parameters of the Data in the message frame utilized as mask (In this example it means all 64 digital outputs shall set status)
  01    02    03    04    05    06    07    08 => Example data as the second 8 parameters of the Data in the message frame as data value of 1 or 0, corresponding to the first 8 bytes)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatusMULTI => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 117 of file FH_DO_SetStatus_R.c.
References FH_DO_MaxPeripheralNumber, FH_DO_MULTI_MaxPeripheralNumberLimit, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DO_ProcessCommand_SetStatusMULTI().