FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH/FH_Root/FH_Perif/FH_DI/Cmd/Init/Init_R/FH_DI_Init_R.h File Reference
FH_DI_Init_R.h File Reference
#include "../../../../../../FH_Root/FH_Perif/FH_DI/FH_DI_Configs/FH_DI_Configs.h"
Functions
FH_ErrorInfo FH_DI_Init_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, FH_DI_Init_FuncPtrModel *FH_DI_Init_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
FH_ErrorInfo FH_DI_InitMULTI_R_Start (FH_RFCommunication_Message *fh_RFCommunication_Message, FH_DI_Init_FuncPtrModel *FH_DI_Init_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
Function Documentation
FH_DI_Init_R_Start()
FH_ErrorInfo FH_DI_Init_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, FH_DI_Init_FuncPtrModel * FH_DI_Init_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DI_Init_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    DI01
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DI01 => It indicates the Digital Input 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_Init => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 58 of file FH_DI_Init_R.c.
References FH_ErrorInfo::error_code, FH_DI_MaxPeripheralNumber, FH_ERROR_CommandData, FH_ERROR_Functions, FH_ERROR_NoInfo, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DI_ProcessCommand_Init().
FH_DI_InitMULTI_R_Start()
FH_ErrorInfo FH_DI_InitMULTI_R_Start (FH_RFCommunication_Message * fh_RFCommunication_Message, FH_DI_Init_FuncPtrModel * FH_DI_Init_FuncPtr)
This function calls the related function in FH_Functions, Section FH_DI (Digital Input) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
fH_DI_Init_FuncPtr The array of function pointers
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    DI01
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DI}    Command=${DI_Commands_InitMULTI}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  01    02    03    04    05    06    07    08 => Example data as the first 8 parameters
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DI => It is the function in the message frame
  DI_Commands_InitMULTI => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 114 of file FH_DI_Init_R.c.
References FH_DI_MaxPeripheralNumber, FH_DI_MULTI_MaxPeripheralNumberLimit, FH_ResetErrorInfo(), fh_RFCommunication_Message, and NULL_PTR.
Referenced by FH_DI_ProcessCommand_InitMULTI().