FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_AO/FH_AO.h File Reference
FH_AO.h File Reference
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output)
Functions in this file, handle RFCommunication (RobotFramework Communication) for all commands related to AO (Analog Output)
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_AO/FH_AO_Configs/FH_AO_Configs.h"
Functions
FH_ErrorInfo FH_AO_RFCommunication (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function is the basic function of handling RFCommunication (RobotFramework Communication) for all the Commands related to the Function AO (Analog Output)
This function is called from FH_RFCommunication()
FH_ErrorInfo FH_AO_ProcessCommand_Init (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function handles FH_AO_Commands_Init command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AO (Analog Output) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AO (Analog Output) according to the first parameter of the Data in the message frame.
FH_ErrorInfo FH_AO_ProcessCommand_SetStatus (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function handles FH_AO_Commands_SetStatus command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AO (Analog Output) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AO (Analog Output) according to the first parameter of the Data in the message frame
(The next 4 parameters after the first one, resemble the analog data to be set as one 32 bit data)
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_AO (Analog Output)
Functions in this file, handle RFCommunication (RobotFramework Communication) for all commands related to AO (Analog Output)
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_AO.h.
Function Documentation
FH_AO_ProcessCommand_Init()
FH_ErrorInfo FH_AO_ProcessCommand_Init (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function handles FH_AO_Commands_Init command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AO (Analog Output) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AO (Analog Output) according to the first parameter of the Data in the message frame.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AO01}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AO}    Command=${AO_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AO01 => It indicates the Analog Output 01
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AO => It is the function in the message frame
  AO_Commands_Init => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 103 of file FH_AO.c.
References FH_ErrorInfo::error_code, FH_AO_Init_C(), FH_AO_Init_H(), FH_AO_Init_S(), FH_AO_MaxPeripheralNumber, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_AO_RFCommunication().
FH_AO_ProcessCommand_SetStatus()
FH_ErrorInfo FH_AO_ProcessCommand_SetStatus (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function handles FH_AO_Commands_SetStatus command
There are 3 main items handled in this function as following:
1 - Verifying the health of the received message
2 - Setting the addresses of the functions in FH_Functions, Section FH_AO (Analog Output) to an array of function pointer
3 - Calling the related function in FH_Functions, Section FH_AO (Analog Output) according to the first parameter of the Data in the message frame
(The next 4 parameters after the first one, resemble the analog data to be set as one 32 bit data)
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${AO01}    F1    C2    01    08
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_AO}    Command=${AO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  AO01 => It indicates the Analog Output 01
  F1    C2    01    08 => Example data as analog value (0xF1C20108) to be set through the <b>Analog Output 01</b>\n
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_AO => It is the function in the message frame
  AO_Commands_SetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 158 of file FH_AO.c.
References FH_ErrorInfo::error_code, FH_AO_MaxPeripheralNumber, FH_AO_SetStatus_C(), FH_AO_SetStatus_H(), FH_AO_SetStatus_S(), FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_AO_RFCommunication().
FH_AO_RFCommunication()
FH_ErrorInfo FH_AO_RFCommunication (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function is the basic function of handling RFCommunication (RobotFramework Communication) for all the Commands related to the Function AO (Analog Output)
This function is called from FH_RFCommunication()
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 50 of file FH_AO.c.
References FH_ErrorInfo::error_code, FH_AO_Commands_Init, FH_AO_Commands_SetStatus, FH_AO_ProcessCommand_Init(), FH_AO_ProcessCommand_SetStatus(), FH_ResetErrorInfo(), FH_RFCommunication_DeviceAddress, fh_RFCommunication_Message, FH_RFCommunication_Send(), and FH_RFCommunication_SendBuf.
Referenced by FH_RFCommunication().