FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_DI/Cmd/GetStatus/GetStatus_S/FH_DI_GetStatus_S.c File Reference
FH_DI_GetStatus_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_DI (Digital Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_DI (Digital Input), FH_DI_GetStatus_DI01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_DI/Cmd/GetStatus/GetStatus_S/FH_DI_GetStatus_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI01/FH_DI01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI02/FH_DI02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI03/FH_DI03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI04/FH_DI04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI05/FH_DI05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI06/FH_DI06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI07/FH_DI07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI08/FH_DI08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI09/FH_DI09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI10/FH_DI10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI11/FH_DI11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI12/FH_DI12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI13/FH_DI13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI14/FH_DI14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI15/FH_DI15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI16/FH_DI16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI17/FH_DI17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI18/FH_DI18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI19/FH_DI19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI20/FH_DI20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI21/FH_DI21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI22/FH_DI22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI23/FH_DI23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI24/FH_DI24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI25/FH_DI25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI26/FH_DI26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI27/FH_DI27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI28/FH_DI28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI29/FH_DI29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI30/FH_DI30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI31/FH_DI31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI32/FH_DI32.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI33/FH_DI33.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI34/FH_DI34.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI35/FH_DI35.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI36/FH_DI36.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI37/FH_DI37.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI38/FH_DI38.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI39/FH_DI39.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI40/FH_DI40.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI41/FH_DI41.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI42/FH_DI42.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI43/FH_DI43.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI44/FH_DI44.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI45/FH_DI45.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI46/FH_DI46.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI47/FH_DI47.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI48/FH_DI48.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI49/FH_DI49.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI50/FH_DI50.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI51/FH_DI51.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI52/FH_DI52.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI53/FH_DI53.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI54/FH_DI54.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI55/FH_DI55.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI56/FH_DI56.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI57/FH_DI57.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI58/FH_DI58.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI59/FH_DI59.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI60/FH_DI60.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI61/FH_DI61.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI62/FH_DI62.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI63/FH_DI63.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DI/FH_DI64/FH_DI64.h"
Functions
void FH_DI_GetStatus_S (FH_DI_GetStatus_FuncPtrModel *FH_DI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_DI (Digital Input), FH_DI_GetStatus_DI01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_DI (Digital Input), Cmd (Command), GetStatus, GetStatus_S (GetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_DI (Digital Input), FH_DI_GetStatus_DI01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DI_GetStatus_S.c.
Function Documentation
FH_DI_GetStatus_S()
void FH_DI_GetStatus_S (FH_DI_GetStatus_FuncPtrModel * FH_DI_GetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_DI (Digital Input), FH_DI_GetStatus_DI01-... to an array of function pointers.
Parameters
FH_DI_GetStatus_FuncPtr An array of function pointers with FH_DI_GetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_DI_GetStatus_S.c.
References FH_DI_GetStatus_DI01(), FH_DI_GetStatus_DI02(), FH_DI_GetStatus_DI03(), FH_DI_GetStatus_DI04(), FH_DI_GetStatus_DI05(), FH_DI_GetStatus_DI06(), FH_DI_GetStatus_DI07(), FH_DI_GetStatus_DI08(), FH_DI_GetStatus_DI09(), FH_DI_GetStatus_DI10(), FH_DI_GetStatus_DI11(), FH_DI_GetStatus_DI12(), FH_DI_GetStatus_DI13(), FH_DI_GetStatus_DI14(), FH_DI_GetStatus_DI15(), FH_DI_GetStatus_DI16(), FH_DI_GetStatus_DI17(), FH_DI_GetStatus_DI18(), FH_DI_GetStatus_DI19(), FH_DI_GetStatus_DI20(), FH_DI_GetStatus_DI21(), FH_DI_GetStatus_DI22(), FH_DI_GetStatus_DI23(), FH_DI_GetStatus_DI24(), FH_DI_GetStatus_DI25(), FH_DI_GetStatus_DI26(), FH_DI_GetStatus_DI27(), FH_DI_GetStatus_DI28(), FH_DI_GetStatus_DI29(), FH_DI_GetStatus_DI30(), FH_DI_GetStatus_DI31(), FH_DI_GetStatus_DI32(), FH_DI_GetStatus_DI33(), FH_DI_GetStatus_DI34(), FH_DI_GetStatus_DI35(), FH_DI_GetStatus_DI36(), FH_DI_GetStatus_DI37(), FH_DI_GetStatus_DI38(), FH_DI_GetStatus_DI39(), FH_DI_GetStatus_DI40(), FH_DI_GetStatus_DI41(), FH_DI_GetStatus_DI42(), FH_DI_GetStatus_DI43(), FH_DI_GetStatus_DI44(), FH_DI_GetStatus_DI45(), FH_DI_GetStatus_DI46(), FH_DI_GetStatus_DI47(), FH_DI_GetStatus_DI48(), FH_DI_GetStatus_DI49(), FH_DI_GetStatus_DI50(), FH_DI_GetStatus_DI51(), FH_DI_GetStatus_DI52(), FH_DI_GetStatus_DI53(), FH_DI_GetStatus_DI54(), FH_DI_GetStatus_DI55(), FH_DI_GetStatus_DI56(), FH_DI_GetStatus_DI57(), FH_DI_GetStatus_DI58(), FH_DI_GetStatus_DI59(), FH_DI_GetStatus_DI60(), FH_DI_GetStatus_DI61(), FH_DI_GetStatus_DI62(), FH_DI_GetStatus_DI63(), FH_DI_GetStatus_DI64(), FH_DI_MaxPeripheralNumber, and NULL_PTR.
Referenced by FH_DI_ProcessCommand_GetStatus(), and FH_DI_ProcessCommand_GetStatusMULTI().