FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_PWMO/Cmd/Init/Init_S/FH_PWMO_Init_S.c File Reference
FH_PWMO_Init_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_PWMO (PWM Output), Cmd (Command), Init, Init_S (Init Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_Init_PWMO01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_PWMO/Cmd/Init/Init_S/FH_PWMO_Init_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO01/FH_PWMO01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO02/FH_PWMO02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO03/FH_PWMO03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO04/FH_PWMO04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO05/FH_PWMO05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO06/FH_PWMO06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO07/FH_PWMO07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO08/FH_PWMO08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO09/FH_PWMO09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO10/FH_PWMO10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO11/FH_PWMO11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO12/FH_PWMO12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO13/FH_PWMO13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO14/FH_PWMO14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO15/FH_PWMO15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO16/FH_PWMO16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO17/FH_PWMO17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO18/FH_PWMO18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO19/FH_PWMO19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO20/FH_PWMO20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO21/FH_PWMO21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO22/FH_PWMO22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO23/FH_PWMO23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO24/FH_PWMO24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO25/FH_PWMO25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO26/FH_PWMO26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO27/FH_PWMO27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO28/FH_PWMO28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO29/FH_PWMO29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO30/FH_PWMO30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO31/FH_PWMO31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_PWMO/FH_PWMO32/FH_PWMO32.h"
Functions
void FH_PWMO_Init_S (FH_PWMO_Init_FuncPtrModel *FH_PWMO_Init_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_Init_PWMO01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_PWMO (PWM Output), Cmd (Command), Init, Init_S (Init Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_Init_PWMO01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_PWMO_Init_S.c.
Function Documentation
FH_PWMO_Init_S()
void FH_PWMO_Init_S (FH_PWMO_Init_FuncPtrModel * FH_PWMO_Init_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_PWMO (PWM Output), FH_PWMO_Init_PWMO01-... to an array of function pointers.
Parameters
FH_PWMO_Init_FuncPtr An array of function pointers with FH_PWMO_Init_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_PWMO_Init_S.c.
References FH_PWMO_Init_PWMO01(), FH_PWMO_Init_PWMO02(), FH_PWMO_Init_PWMO03(), FH_PWMO_Init_PWMO04(), FH_PWMO_Init_PWMO05(), FH_PWMO_Init_PWMO06(), FH_PWMO_Init_PWMO07(), FH_PWMO_Init_PWMO08(), FH_PWMO_Init_PWMO09(), FH_PWMO_Init_PWMO10(), FH_PWMO_Init_PWMO11(), FH_PWMO_Init_PWMO12(), FH_PWMO_Init_PWMO13(), FH_PWMO_Init_PWMO14(), FH_PWMO_Init_PWMO15(), FH_PWMO_Init_PWMO16(), FH_PWMO_Init_PWMO17(), FH_PWMO_Init_PWMO18(), FH_PWMO_Init_PWMO19(), FH_PWMO_Init_PWMO20(), FH_PWMO_Init_PWMO21(), FH_PWMO_Init_PWMO22(), FH_PWMO_Init_PWMO23(), FH_PWMO_Init_PWMO24(), FH_PWMO_Init_PWMO25(), FH_PWMO_Init_PWMO26(), FH_PWMO_Init_PWMO27(), FH_PWMO_Init_PWMO28(), FH_PWMO_Init_PWMO29(), FH_PWMO_Init_PWMO30(), FH_PWMO_Init_PWMO31(), FH_PWMO_Init_PWMO32(), FH_PWMO_MaxPeripheralNumber, and NULL_PTR.
Referenced by FH_PWMO_ProcessCommand_Init().