FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.c File Reference
FH_GeneralFunctions.c File Reference
File Map:
FH_Root, Section FH_General, FH_GeneralFunctions
All different possible general functions utilized in different parts of the code, go here
#include "../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
Functions
uint16_t FH_ConvertUint8ToUint16 (uint8_t *fh_Uint8)
This function converts two 8 bits data (uint8_t) to one 16 bits data (uint16_t)
uint32_t FH_ConvertUint8ToUint32 (uint8_t *fh_Uint8)
This function converts four 8 bits data (uint8_t) to one 32 bits data (uint32_t)
Detailed Description
File Map:
FH_Root, Section FH_General, FH_GeneralFunctions
All different possible general functions utilized in different parts of the code, go here
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_GeneralFunctions.c.
Function Documentation
FH_ConvertUint8ToUint16()
uint16_t FH_ConvertUint8ToUint16 (uint8_t * fh_Uint8)
This function converts two 8 bits data (uint8_t) to one 16 bits data (uint16_t)
Parameters
fh_Uint8 Pointer to the two 8 bits data (uint8_t)
Returns
The one 16 bits data (uint16_t)
Note
For this to happen, FH_Uint8Uint16 enumeration defined in FH_GeneralFunctions.h is utilized
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 37 of file FH_GeneralFunctions.c.
References FH_Uint8Uint16::bytes, and FH_Uint8Uint16::value.
Referenced by FH_CAN_SSD16_CAN01(), FH_CAN_SSD16_CAN02(), FH_CAN_SSD16_CAN03(), FH_CAN_SSD16_CAN04(), FH_UART_SSD16_UART01(), FH_UART_SSD16_UART02(), FH_UART_SSD16_UART03(), and FH_UART_SSD16_UART04().
FH_ConvertUint8ToUint32()
uint32_t FH_ConvertUint8ToUint32 (uint8_t * fh_Uint8)
This function converts four 8 bits data (uint8_t) to one 32 bits data (uint32_t)
Parameters
fh_Uint8 Pointer to the four 8 bits data (uint8_t)
Returns
The one 32 bits data (uint32_t)
Note
For this to happen, FH_Uint8Uint32 enumeration defined in FH_GeneralFunctions.h is utilized
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 58 of file FH_GeneralFunctions.c.
References FH_Uint8Uint32::bytes, and FH_Uint8Uint32::value.
Referenced by FH_AO_SetStatus_AO01(), FH_CAN_ReceiveW_CAN01(), FH_CAN_ReceiveW_CAN02(), FH_CAN_ReceiveW_CAN03(), FH_CAN_ReceiveW_CAN04(), FH_CAN_ReceiveW_H(), FH_CAN_SSD32_CAN01(), FH_CAN_SSD32_CAN02(), FH_CAN_SSD32_CAN03(), FH_CAN_SSD32_CAN04(), FH_PWMO_SetStatus_PWMO01(), FH_UART_ReceiveW_H(), FH_UART_ReceiveW_UART01(), FH_UART_ReceiveW_UART02(), FH_UART_ReceiveW_UART03(), FH_UART_ReceiveW_UART04(), FH_UART_SSD32_UART01(), FH_UART_SSD32_UART02(), FH_UART_SSD32_UART03(), and FH_UART_SSD32_UART04().