FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_DO/Cmd/SetStatus/SetStatus_S/FH_DO_SetStatus_S.c File Reference
FH_DO_SetStatus_S.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_DO (Digital Output), FH_DO_SetStatus_DO01-... to an array of function pointers
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_DO/Cmd/SetStatus/SetStatus_S/FH_DO_SetStatus_S.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO01/FH_DO01.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO02/FH_DO02.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO03/FH_DO03.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO04/FH_DO04.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO05/FH_DO05.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO06/FH_DO06.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO07/FH_DO07.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO08/FH_DO08.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO09/FH_DO09.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO10/FH_DO10.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO11/FH_DO11.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO12/FH_DO12.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO13/FH_DO13.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO14/FH_DO14.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO15/FH_DO15.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO16/FH_DO16.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO17/FH_DO17.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO18/FH_DO18.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO19/FH_DO19.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO20/FH_DO20.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO21/FH_DO21.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO22/FH_DO22.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO23/FH_DO23.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO24/FH_DO24.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO25/FH_DO25.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO26/FH_DO26.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO27/FH_DO27.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO28/FH_DO28.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO29/FH_DO29.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO30/FH_DO30.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO31/FH_DO31.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO32/FH_DO32.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO33/FH_DO33.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO34/FH_DO34.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO35/FH_DO35.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO36/FH_DO36.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO37/FH_DO37.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO38/FH_DO38.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO39/FH_DO39.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO40/FH_DO40.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO41/FH_DO41.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO42/FH_DO42.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO43/FH_DO43.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO44/FH_DO44.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO45/FH_DO45.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO46/FH_DO46.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO47/FH_DO47.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO48/FH_DO48.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO49/FH_DO49.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO50/FH_DO50.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO51/FH_DO51.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO52/FH_DO52.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO53/FH_DO53.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO54/FH_DO54.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO55/FH_DO55.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO56/FH_DO56.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO57/FH_DO57.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO58/FH_DO58.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO59/FH_DO59.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO60/FH_DO60.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO61/FH_DO61.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO62/FH_DO62.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO63/FH_DO63.h"
#include "../../../../../../../FH_Embedded/FH_Functions/FH_DO/FH_DO64/FH_DO64.h"
Functions
void FH_DO_SetStatus_S (FH_DO_SetStatus_FuncPtrModel *FH_DO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_DO (Digital Output), FH_DO_SetStatus_DO01-... to an array of function pointers.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_S (SetStatus Set Address)
Functions in this file, set the address of the defined FH_Functions, Section FH_DO (Digital Output), FH_DO_SetStatus_DO01-... to an array of function pointers
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DO_SetStatus_S.c.
Function Documentation
FH_DO_SetStatus_S()
void FH_DO_SetStatus_S (FH_DO_SetStatus_FuncPtrModel * FH_DO_SetStatus_FuncPtr)
This function sets the address of the defined FH_Functions, Section FH_DO (Digital Output), FH_DO_SetStatus_DO01-... to an array of function pointers.
Parameters
FH_DO_SetStatus_FuncPtr An array of function pointers with FH_DO_SetStatus_FuncPtrModel model
Returns
None
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 232 of file FH_DO_SetStatus_S.c.
References FH_DO_MaxPeripheralNumber, FH_DO_SetStatus_DO01(), FH_DO_SetStatus_DO02(), FH_DO_SetStatus_DO03(), FH_DO_SetStatus_DO04(), FH_DO_SetStatus_DO05(), FH_DO_SetStatus_DO06(), FH_DO_SetStatus_DO07(), FH_DO_SetStatus_DO08(), FH_DO_SetStatus_DO09(), FH_DO_SetStatus_DO10(), FH_DO_SetStatus_DO11(), FH_DO_SetStatus_DO12(), FH_DO_SetStatus_DO13(), FH_DO_SetStatus_DO14(), FH_DO_SetStatus_DO15(), FH_DO_SetStatus_DO16(), FH_DO_SetStatus_DO17(), FH_DO_SetStatus_DO18(), FH_DO_SetStatus_DO19(), FH_DO_SetStatus_DO20(), FH_DO_SetStatus_DO21(), FH_DO_SetStatus_DO22(), FH_DO_SetStatus_DO23(), FH_DO_SetStatus_DO24(), FH_DO_SetStatus_DO25(), FH_DO_SetStatus_DO26(), FH_DO_SetStatus_DO27(), FH_DO_SetStatus_DO28(), FH_DO_SetStatus_DO29(), FH_DO_SetStatus_DO30(), FH_DO_SetStatus_DO31(), FH_DO_SetStatus_DO32(), FH_DO_SetStatus_DO33(), FH_DO_SetStatus_DO34(), FH_DO_SetStatus_DO35(), FH_DO_SetStatus_DO36(), FH_DO_SetStatus_DO37(), FH_DO_SetStatus_DO38(), FH_DO_SetStatus_DO39(), FH_DO_SetStatus_DO40(), FH_DO_SetStatus_DO41(), FH_DO_SetStatus_DO42(), FH_DO_SetStatus_DO43(), FH_DO_SetStatus_DO44(), FH_DO_SetStatus_DO45(), FH_DO_SetStatus_DO46(), FH_DO_SetStatus_DO47(), FH_DO_SetStatus_DO48(), FH_DO_SetStatus_DO49(), FH_DO_SetStatus_DO50(), FH_DO_SetStatus_DO51(), FH_DO_SetStatus_DO52(), FH_DO_SetStatus_DO53(), FH_DO_SetStatus_DO54(), FH_DO_SetStatus_DO55(), FH_DO_SetStatus_DO56(), FH_DO_SetStatus_DO57(), FH_DO_SetStatus_DO58(), FH_DO_SetStatus_DO59(), FH_DO_SetStatus_DO60(), FH_DO_SetStatus_DO61(), FH_DO_SetStatus_DO62(), FH_DO_SetStatus_DO63(), FH_DO_SetStatus_DO64(), and NULL_PTR.
Referenced by FH_DO_ProcessCommand_SetStatus(), and FH_DO_ProcessCommand_SetStatusMULTI().