FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Setup/FH_RFCommunication/FH_RFCommunication.h File Reference
FH_RFCommunication.h File Reference
File Map:
FH_Setup, Section FH_RFCommunication
This file is header file of the main source file of the communication between RobotFramework and the micro-controller on which FH source code is ported
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
#include "../../../FH_Embedded/FH_Root/FH_General/FH_ErrorInfo/FH_ErrorInfo.h"
Functions
FH_ErrorInfo FH_RFCommunication ()
This function verifies if a complete message from RobotFramework is received or not and if yes, calls the related function
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
.
FH_ErrorInfo FH_RFCommunication_Init ()
This function initializes the Communication Dedicated UART
The Communication Dedicated UART could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
FH_ErrorInfo FH_RFCommunication_Send (char *DataString)
This function sends data through the Communication Dedicated UART
The Communication Dedicated UART could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
FH_ErrorInfo FH_RFCommunication_Receive ()
This function is the main source of receiving a complete message from RobotFramework
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
.
Detailed Description
File Map:
FH_Setup, Section FH_RFCommunication
This file is header file of the main source file of the communication between RobotFramework and the micro-controller on which FH source code is ported
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_RFCommunication.h.
Function Documentation
FH_RFCommunication()
FH_ErrorInfo FH_RFCommunication ()
This function verifies if a complete message from RobotFramework is received or not and if yes, calls the related function
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_RFCommunication_ReceiveBuf and FH_RFCommunication_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the Communication Dedicated UART in a separate c file
For this to happen, FH user shall just include FH_RFCommunication_GlobalVariables.h there
In other word, FH_RFCommunication_ReceiveBuf array shall receive every byte of the received data there with FH_RFCommunication_ReceiveBufIndex as index of the array
Attention
FH_RFCommunication_Message is the structure for receiving the message frame from RobotFramework
The first data in this structure is the DeviceAddress
If a message (from RobotFramework) with a different DeviceAddress than the one set in FH_DeviceAddress.h is received, it will be ignored and not processed
Note
If there is just one device (or card), there is no need for the FH user to change the default address which is already 0x01
In this case, the address of the message in the message frame (in RobotFramework) shall be set to 01
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DO01}    ${DO_Set}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO01 => It indicates the Digital Output 01
  DO_Set => It indicates the Digital Output 01 shall be Set (DO_Reset indicates the Digital Output 01 shall be Reset)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatus => It is the command of the function in the message frame
Note
If at least one byte of data is received through the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, a complete message shall be received in a maximum defined timeout
The received data in the ISR (Interrupt Service Routine) will be ignored if the complete message will not be received within the defined timeout
For this to happen, FH_GlobalTimeCounter is utilized to calculate the maximum timeout
FH_RFCommunication_ReceiveBufMaxTimeout is the defined maximum timeout for every byte
In the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, FH_GlobalTimeCounter shall be reset after receiving every byte of data
If at least one byte of data is received through the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, a complete message shall be received in a maximum defined timeout
The received data in the ISR (Interrupt Service Routine) will be ignored if the complete message will not be received within the defined timeout
For this to happen, FH_GlobalTimeCounter is utilized to calculate the maximum timeout
FH_RFCommunication_ReceiveBufMaxTimeout is the defined maximum timeout for every byte
In the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, FH_GlobalTimeCounter shall be reset after receiving every byte of data
Warning
If FH user would not increment the FH_GlobalTimeCounter in a timer ISR (Interrupt Service Routine) every 1 mili-second, there will be a malfunction here
Attention
FH user could left this function intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition at line 483 of file FH_RFCommunication.c.
References FH_ErrorInfo::error_code, FH_AI_RFCommunication(), FH_AO_RFCommunication(), FH_CAN_RFCommunication(), FH_DI_RFCommunication(), FH_DO_RFCommunication(), FH_ERROR_OK, FH_PWMI_RFCommunication(), FH_PWMO_RFCommunication(), FH_ResetErrorInfo(), fh_RFCommunication_Message, FH_RFCommunication_Receive(), FH_UART_RFCommunication(), RFCommunication_Function_AI, RFCommunication_Function_AO, RFCommunication_Function_CAN, RFCommunication_Function_DI, RFCommunication_Function_DO, RFCommunication_Function_PWMI, RFCommunication_Function_PWMO, and RFCommunication_Function_UART.
FH_RFCommunication_Init()
FH_ErrorInfo FH_RFCommunication_Init ()
This function initializes the Communication Dedicated UART
The Communication Dedicated UART could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested UART here.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
Warning
To be able to send or receive data through the Communication Dedicated UART of the micro-controller on which FH source code is ported, this function shall be invoked once in the main.c file firstly
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 158 of file FH_RFCommunication.c.
References FH_ResetErrorInfo(), and FH_RFCommunication_ReceiveBufIndex.
FH_RFCommunication_Receive()
FH_ErrorInfo FH_RFCommunication_Receive ()
This function is the main source of receiving a complete message from RobotFramework
The micro-controller on which FH source code is ported, could be simply utilized in a RS485 network
In other word, multiple devices or multiple cards could be simply utilized where every device or every card has its own address
Address of the device (or card) for every device (or card) is set by FH user in FH_DeviceAddress.h
An interested UART (called Communication Dedicated UART) by the FH user for the communication between RobotFramework and the micro-controller on which FH source code is ported, shall be dedicated
.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
FH user shall use FH_RFCommunication_ReceiveBuf and FH_RFCommunication_ReceiveBufIndex in the receive ISR (Interrupt Service Routine) of the Communication Dedicated UART in a separate c file
For this to happen, FH user shall just include FH_RFCommunication_GlobalVariables.h there
In other word, FH_RFCommunication_ReceiveBuf array shall receive every byte of the received data there with FH_RFCommunication_ReceiveBufIndex as index of the array
Attention
FH_RFCommunication_Message is the structure for receiving the message frame from RobotFramework
The first data in this structure is the DeviceAddress
If a message (from RobotFramework) with a different DeviceAddress than the one set in FH_DeviceAddress.h is received, it will be ignored and not processed
Note
If there is just one device (or card), there is no need for the FH user to change the default address which is already 0x01
In this case, the address of the message in the message frame (in RobotFramework) shall be set to 01
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DO01}    ${DO_Set}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO01 => It indicates the Digital Output 01
  DO_Set => It indicates the Digital Output 01 shall be Set (DO_Reset indicates the Digital Output 01 shall be Reset)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatus => It is the command of the function in the message frame
Note
If at least one byte of data is received through the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, a complete message shall be received in a maximum defined timeout
The received data in the ISR (Interrupt Service Routine) will be ignored if the complete message will not be received within the defined timeout
For this to happen, FH_GlobalTimeCounter is utilized to calculate the maximum timeout
FH_RFCommunication_ReceiveBufMaxTimeout is the defined maximum timeout for every byte
In the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, FH_GlobalTimeCounter shall be reset after receiving every byte of data
If at least one byte of data is received through the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, a complete message shall be received in a maximum defined timeout
The received data in the ISR (Interrupt Service Routine) will be ignored if the complete message will not be received within the defined timeout
For this to happen, FH_GlobalTimeCounter is utilized to calculate the maximum timeout
FH_RFCommunication_ReceiveBufMaxTimeout is the defined maximum timeout for every byte
In the ISR (Interrupt Service Routine) of the Communication Dedicated UART by the FH user, FH_GlobalTimeCounter shall be reset after receiving every byte of data
Warning
If FH user would not increment the FH_GlobalTimeCounter in a timer ISR (Interrupt Service Routine) every 1 mili-second, there will be a malfunction here
Attention
FH user could left this function intact
Note
FH_RFCommunication_Message is the structure for receiving the message frame from RobotFramework
FH_RFCommunication_State is the enumeration utilized as state machine to collect the different blocks of the message frame from RobotFramework
It is initialized with RFCommunication_STATE_IDLE to be ready to collect a new message from RobotFramework
FH_RFCommunication_ReceiveBufReadIndex is the index of the data which is read from the FH_RFCommunication_ReceiveBuf to be processed
It is used to help process the received data through the Communication Dedicated UART
FH_RFCommunication_Message_DataIndex is the index of the data part of the message frame
It is used in FH_RFCommunication_Receive function to help collect the received data part of the message frame through the Communication Dedicated UART For more information, refer to FH_RFCommunication_Message
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition at line 295 of file FH_RFCommunication.c.
References FH_ErrorInfo::error_code, FH_ERROR_MessageFrame, FH_ERROR_NoInfo, FH_ERROR_OK, FH_ERROR_Timeout, FH_GlobalTimeCounter, FH_ResetErrorInfo(), FH_RFCommunication_DeviceAddress, fh_RFCommunication_Message, FH_RFCommunication_Message_DataIndex, FH_RFCommunication_MinCommandSize, FH_RFCommunication_ReceiveBuf, FH_RFCommunication_ReceiveBufIndex, FH_RFCommunication_ReceiveBufMaxTimeout, FH_RFCommunication_ReceiveBufReadIndex, fh_RFCommunication_State, RFCommunication_Command, RFCommunication_DataLength, RFCommunication_DeviceAddress, RFCommunication_Function, RFCommunication_STATE_Checksum, RFCommunication_STATE_Command, RFCommunication_STATE_Data, RFCommunication_STATE_DataLength, RFCommunication_STATE_DeviceAddress, RFCommunication_STATE_Function, RFCommunication_STATE_IDLE, and RFCommunication_STATE_MessageReceived.
Referenced by FH_RFCommunication().
FH_RFCommunication_Send()
FH_ErrorInfo FH_RFCommunication_Send (char * DataString)
This function sends data through the Communication Dedicated UART
The Communication Dedicated UART could be any interested UART of the micro-controller on which FH source code is ported
FH user should call the send function of the interested UART here.
Parameters
DataString a null terminated string of data to be sent
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
Warning
To be able to send data through the Communication Dedicated UART of the micro-controller on which FH source code is ported, the FH_RFCommunication_Init function shall be invoked once in the main.c file firstly
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 195 of file FH_RFCommunication.c.
References FH_ResetErrorInfo().
Referenced by FH_AI_RFCommunication(), FH_AO_RFCommunication(), FH_CAN_RFCommunication(), FH_DI_RFCommunication(), FH_DO_RFCommunication(), FH_PWMI_RFCommunication(), FH_PWMO_RFCommunication(), and FH_UART_RFCommunication().