FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Root/FH_Perif/FH_DO/Cmd/SetStatus/SetStatus_H/FH_DO_SetStatus_H.c File Reference
FH_DO_SetStatus_H.c File Reference
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_H (SetStatus Health)
Functions in this file, verify the health of the different message frames related to DO (Digital Output)
#include "../../../../../../../FH_Embedded/FH_Root/FH_Perif/FH_DO/Cmd/SetStatus/SetStatus_H/FH_DO_SetStatus_H.h"
#include "../../../../../../../FH_Embedded/FH_Root/FH_General/FH_GeneralFunctions/FH_GeneralFunctions.h"
#include "../../../../../../../FH_Embedded/FH_Setup/FH_DeviceAddress/FH_DeviceAddress.h"
Functions
FH_ErrorInfo FH_DO_SetStatus_H (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function verifies the health of FH_DO_Commands_SetStatus command.
FH_ErrorInfo FH_DO_SetStatusMULTI_H (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function verifies the health of FH_DO_Commands_SetStatusMULTI command.
Detailed Description
File Map:
FH_Root, Section FH_Perif, FH_DO (Digital Output), Cmd (Command), SetStatus, SetStatus_H (SetStatus Health)
Functions in this file, verify the health of the different message frames related to DO (Digital Output)
Attention
FH user could left this file intact
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_DO_SetStatus_H.c.
Function Documentation
FH_DO_SetStatus_H()
FH_ErrorInfo FH_DO_SetStatus_H (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function verifies the health of FH_DO_Commands_SetStatus command.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${DO01}    ${DO_Set}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  DO01 => It indicates the Digital Output 01
  DO_Set => It indicates the Digital Output 01 shall be Set (DO_Reset indicates the Digital Output 01 shall be Reset)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatus => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 57 of file FH_DO_SetStatus_H.c.
References FH_ErrorInfo::error_code, FH_DO_MaxPeripheralNumber, FH_DO_MinCommandSize_SetStatus, FH_ERROR_MessageFrame, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_DO_ProcessCommand_SetStatus().
FH_DO_SetStatusMULTI_H()
FH_ErrorInfo FH_DO_SetStatusMULTI_H (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function verifies the health of FH_DO_Commands_SetStatusMULTI command.
Parameters
fh_RFCommunication_Message The message frame set by RobotFramework
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    FF    FF    FF    FF    FF    FF    FF    FF    01    02    03    04    05    06    07    08
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_DO}    Command=${DO_Commands_SetStatusMULTI}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  FF    FF    FF    FF    FF    FF    FF    FF => Example data as the first 8 parameters of the Data in the message frame utilized as mask (In this example it means all 64 digital outputs shall set status
  01    02    03    04    05    06    07    08 => Example data as the second 8 parameters of the Data in the message frame as data value of 1 or 0, corresponding to the first 8 bytes)
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_DO => It is the function in the message frame
  DO_Commands_SetStatusMULTI => It is the command of the function in the message frame
Returns
FH_ErrorInfo is returned
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 121 of file FH_DO_SetStatus_H.c.
References FH_ErrorInfo::error_code, FH_DO_MinCommandSize_SetStatusMULTI, FH_ERROR_MessageFrame, FH_ERROR_OK, FH_ResetErrorInfo(), and fh_RFCommunication_Message.
Referenced by FH_DO_ProcessCommand_SetStatusMULTI().