FH: D:/Hasirchi/!HIL/Embedded/Stm32CubeIDE/project/Core/FH_Embedded/FH_Functions/FH_PWMI/FH_PWMI22/FH_PWMI22.h File Reference
FH_PWMI22.h File Reference
File Map:
FH_Functions, Section FH_PWMI (PWM Input), Peripheral FH_PWMI22 (PWM Input 22)
(The PWMI22 (PWM Input 22) could be any interested PWM Input of the micro-controller on which FH source code is ported)
#include "../../../../FH_Embedded/FH_Root/FH_Perif/FH_PWMI/FH_PWMI_Configs/FH_PWMI_Configs.h"
#include "../../../../FH_Embedded/FH_Setup/FH_RFCommunication/FH_RFCommunication_GlobalVariables.h"
Functions
FH_ErrorInfo FH_PWMI_Init_PWMI22 (FH_RFCommunication_Message *fh_RFCommunication_Message)
This function initializes the PWM Input 22
The PWM Input 22 could be any interested PWM Input of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested PWM Input here.
FH_ErrorInfo FH_PWMI_GetStatus_PWMI22 (FH_RFCommunication_Message *fh_RFCommunication_Message, uint32_t *fh_Frequency, uint8_t *fh_DutyCycle)
This function reads the PWM Input 22
The PWM Input 22 could be any interested PWM Input of the micro-controller on which FH source code is ported
FH user should call the read function of the interested PWM Input here.
Detailed Description
File Map:
FH_Functions, Section FH_PWMI (PWM Input), Peripheral FH_PWMI22 (PWM Input 22)
(The PWMI22 (PWM Input 22) could be any interested PWM Input of the micro-controller on which FH source code is ported)
© COPYRIGHT(c) 2024 ... All rights reserved
This software component is licensed by ...
You may obtain a copy of the license at: ...
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
For more information refer to ...
Definition in file FH_PWMI22.h.
Function Documentation
FH_PWMI_GetStatus_PWMI22()
FH_ErrorInfo FH_PWMI_GetStatus_PWMI22 (FH_RFCommunication_Message * fh_RFCommunication_Message, uint32_t * fh_Frequency, uint8_t * fh_DutyCycle)
This function reads the PWM Input 22
The PWM Input 22 could be any interested PWM Input of the micro-controller on which FH source code is ported
FH user should call the read function of the interested PWM Input here.
Parameters
Data *Data will be set with the value of PWM Input 22
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${PWMI22}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_PWMI}    Command=${PWMI_Commands_GetStatus}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  PWMI22 => It indicates the PWM Input 22
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_PWMI => It is the function in the message frame
  PWMI_Commands_GetStatus => It is the command of the function in the message frame
Warning
To be able to read the PWM Input 22 of the micro-controller on which FH source code is ported, the FH_PWMI_Init_PWMI22 function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_PWMI_GetStatus_PWMI22 function from RobotFramework, FH_PWMI_Init_PWMI22 function shall be invoked in order to initialize the PWM Input
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 129 of file FH_PWMI22.c.
References FH_ResetErrorInfo().
Referenced by FH_PWMI_GetStatus_S().
FH_PWMI_Init_PWMI22()
FH_ErrorInfo FH_PWMI_Init_PWMI22 (FH_RFCommunication_Message * fh_RFCommunication_Message)
This function initializes the PWM Input 22
The PWM Input 22 could be any interested PWM Input of the micro-controller on which FH source code is ported
FH user should call the initialization function of the interested PWM Input here.
Parameters
None
Returns
FH_ErrorInfo is returned
Note
To have a clean code, just include the related header file
Then just call the function here
  ==============================================================================
                        ##### RobotFramework Example #####
  ==============================================================================
  @{MessageData} =    Create List    ${PWMI22}
  &{Message}     =    Create Dictionary    DeviceAddress=${DeviceAdress_01}    Function=${Function_PWMI}    Command=${PWMI_Commands_Init}    Data=@{MessageData}
  ${Result}    SendMessage    &{Message}
  Comments:
  PWMI22 => It indicates the PWM Input 22
  DeviceAdress_01 => It shall be equal to the address of the device: FH_RFCommunication_DeviceAddress
  Function_PWMI => It is the function in the message frame
  PWMI_Commands_Init => It is the command of the function in the message frame
Warning
To be able to read the PWM Input 22 of the micro-controller on which FH source code is ported, this function shall be invoked once by RobotFramework firstly
In other words, before invoking FH_PWMI_GetStatus_PWMI22 function from RobotFramework, this function shall be invoked in order to initialize the PWM Input
Author
Vahid Hasirchi (vahid.nosp@m..has.nosp@m.irchi.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Definition at line 78 of file FH_PWMI22.c.
References FH_ResetErrorInfo().
Referenced by FH_PWMI_Init_S().